import {emitInterface} from "./emitTypes";
import {friendlyHookNames} from "./hookNames";
import {assertSyncCollectionName, assertTsIdentifier, emitTsString} from "./safeIdentifiers";
import type {CodegenConfigFile, DiscoveredCollection} from "./types";

const GENERATED_HEADER = `// GENERATED by @terreno/syncdb (terreno-syncdb-codegen). Do not edit.
// Friendly names (useTodos / useTodo / useCreateTodo / …) so this file can
// coexist with RTK openApiSdk.ts. Mutation triggers are synchronous
// ({mutationId, id}) — there is no .unwrap() or per-call isLoading.
`;

const retriesLiteral = (retries?: boolean | number): string => {
  if (retries === undefined) {
    return "";
  }
  if (retries === false) {
    return ", retries: false";
  }
  if (retries === true) {
    return ", retries: true";
  }
  if (typeof retries === "number" && Number.isFinite(retries)) {
    return `, retries: ${retries}`;
  }
  throw new Error(`Invalid retries override: ${JSON.stringify(retries)}`);
};

export const emitSdk = ({
  collections,
  config,
}: {
  collections: DiscoveredCollection[];
  config?: CodegenConfigFile;
}): string => {
  const sdkImportPath = config?.sdkImportPath ?? "@terreno/syncdb/react";
  const typeBlocks: string[] = [];
  const hookBlocks: string[] = [];
  const names: string[] = [];

  for (const collection of collections) {
    const collectionName = assertSyncCollectionName({
      label: "collection",
      value: collection.collection,
    });
    const entityName = assertTsIdentifier({
      label: "entity schema name",
      value: collection.entityName,
    });
    const createName = assertTsIdentifier({
      label: "create body name",
      value: collection.createName,
    });
    const updateName = assertTsIdentifier({
      label: "update body name",
      value: collection.updateName,
    });
    names.push(collectionName);
    typeBlocks.push(emitInterface({name: entityName, schema: collection.entitySchema}));
    typeBlocks.push(emitInterface({name: createName, schema: collection.createSchema}));
    typeBlocks.push(emitInterface({name: updateName, schema: collection.updateSchema}));

    const hooks = friendlyHookNames({
      collection: collection.collection,
      entityName,
    });
    const list = assertTsIdentifier({label: "hook name", value: hooks.list});
    const read = assertTsIdentifier({label: "hook name", value: hooks.read});
    const create = assertTsIdentifier({label: "hook name", value: hooks.create});
    const update = assertTsIdentifier({label: "hook name", value: hooks.update});
    const remove = assertTsIdentifier({label: "hook name", value: hooks.remove});
    const window = assertTsIdentifier({label: "hook name", value: hooks.window});
    const retries = retriesLiteral(collection.retries);
    hookBlocks.push(`export const {
  useListQuery: ${list},
  useReadQuery: ${read},
  useCreateMutation: ${create},
  useUpdateMutation: ${update},
  useDeleteMutation: ${remove},
  useWindowQuery: ${window},
} = createCollectionHooks<${entityName}, ${createName}, ${updateName}>({collection: ${emitTsString(collectionName)}${retries}});`);
  }

  const collectionsLiteral = names.map((name) => emitTsString(name)).join(", ");
  return [
    GENERATED_HEADER,
    `import {createCollectionHooks} from ${emitTsString(sdkImportPath)};`,
    "",
    typeBlocks.join("\n\n"),
    "",
    "/** Collections with sync enabled on the backend; pass to createSyncDb. */",
    `export const SYNC_COLLECTIONS = [${collectionsLiteral}] as const;`,
    "",
    hookBlocks.join("\n\n"),
    "",
  ].join("\n");
};

export const applyRetriesOverrides = ({
  collections,
  overrides,
}: {
  collections: DiscoveredCollection[];
  overrides?: Record<string, {retries?: boolean | number}>;
}): DiscoveredCollection[] => {
  if (!overrides) {
    return collections;
  }
  return collections.map((collection) => {
    const retries = overrides[collection.collection]?.retries;
    if (retries === undefined) {
      return collection;
    }
    return {...collection, retries};
  });
};
