/**
 * Caps shared by the schema, the prompt, and the reference page.
 */
export const BLOCK_LIMITS = {
  actionElementsMax: 25,
  badgeTextMaxLength: 80,
  barCategoryWarning: 60,
  blockTextMaxLength: 4_000,
  cardTitleMaxLength: 120,
  columnsMax: 4,
  columnsMin: 2,
  contextTextMaxLength: 280,
  datasetColumnMax: 12,
  datasetRowMax: 500,
  documentTextMaxLength: 20_000,
  donutSliceWarning: 8,
  headingTextMaxLength: 200,
  htmlMaxBytes: 100_000,
  maxBlocks: 50,
  maxDatasets: 8,
  maxDepth: 2,
  metricDeltaMaxLength: 40,
  metricHelperMaxLength: 120,
  metricLabelMaxLength: 80,
  metricValueMaxLength: 80,
  refLimitMax: 1_000,
  stepperDecimalsMax: 3,
  stepperIdMaxLength: 54,
  stepperItemsMax: 12,
  stepperItemUnitMaxLength: 20,
  stepperLabelMaxLength: 80,
  stepperNoteMaxLength: 280,
  stepperUnitMaxLength: 40,
} as const;
