// This takes the autogenerated SDK and adds some extra functionality to it. For example,
// we can add extra tags to endpoints.

import {generateTags, realtimeDocument, realtimeList} from "@terreno/rtk";

import {addTagTypes, openapi} from "./openApiSdk";

/** Tag types used by generateTags — todos are excluded; their cache is websocket-only. */
const CACHE_TAG_TYPES = addTagTypes.filter((tag) => tag !== "todos");

const TODO_REALTIME_ENDPOINTS = {
  deleteTodosById: {
    invalidatesTags: [] as const,
  },
  getTodos: {
    onCacheEntryAdded: realtimeList("todos"),
    providesTags: () => [] as const,
  },
  getTodosById: {
    onCacheEntryAdded: realtimeDocument("todos"),
    providesTags: () => [] as const,
  },
  patchTodosById: {
    invalidatesTags: [] as const,
  },
  postTodos: {
    invalidatesTags: [] as const,
  },
};

// This is where we can modify the SDK. For example,
// we can add a transformResponse to the endpoints or we can add extra tags. We can also add extra
// endpoints, since we don't automatically generate for endpoints that don't use the router
// currently.

// Profile response type — emptyApi's base query already unwraps the `data` envelope
export interface ProfileResponse {
  _id: string;
  id: string;
  email: string;
  name: string;
  admin?: boolean;
  emailVerified?: boolean;
  permissions?: Record<string, readonly string[]>;
  roles?: string[];
}

// AI Request Explorer types
interface AIRequestExplorerItem {
  _id: string;
  aiModel: string;
  created: string;
  error?: string;
  prompt: string;
  requestType: string;
  response?: string;
  responseTime?: number;
  tokensUsed?: number;
  user?: {email?: string; name?: string};
  userId?: string;
}

export interface AIRequestExplorerResponse {
  data: AIRequestExplorerItem[];
  limit: number;
  more: boolean;
  page: number;
  total: number;
}

export interface AIRequestExplorerParams {
  endDate?: string;
  limit?: number;
  page?: number;
  requestType?: string;
  startDate?: string;
}

// Selectable AI chat model option returned by GET /ai/models
interface AiModelOption {
  label: string;
  value: string;
}

export interface AiModelsResponse {
  models: AiModelOption[];
}

// Profile update request type
export interface UpdateProfileRequest {
  name?: string;
  email?: string;
  password?: string;
}

export interface SetAdminUserPasswordRequest {
  id: string;
  password: string;
}

// GptHistory endpoints are hand-maintained: nested modelRouter mounts under /gpt/histories
// are not always present in the generated OpenAPI SDK after regen.
type GptHistoryAskKind = "choice" | "confirm";

interface GptHistoryPromptAsk {
  kind: GptHistoryAskKind;
  status: "pending" | "answered" | "cancelled";
}

interface GptHistoryPrompt {
  args?: Record<string, unknown>;
  /** Set on tool-call rows where the model asked the user a question; `args` holds the ask input. */
  ask?: GptHistoryPromptAsk;
  content?: Array<{
    filename?: string;
    mimeType?: string;
    text?: string;
    type: string;
    url?: string;
  }>;
  model?: string;
  result?: unknown;
  text: string;
  toolCallId?: string;
  toolName?: string;
  type: "assistant" | "system" | "tool-call" | "tool-result" | "user";
}

/** The ask a conversation is waiting on. Only the chat turn writes it, so clients never send it. */
interface GptHistoryPendingAsk {
  input: Record<string, unknown>;
  kind: GptHistoryAskKind;
  simple: Record<string, unknown>;
  toolCallId: string;
}

export interface GptHistory {
  _id: string;
  created: string;
  id: string;
  pendingAsk?: GptHistoryPendingAsk;
  prompts: GptHistoryPrompt[];
  title?: string;
  updated: string;
  userId: string;
}

export interface GptHistoriesListResponse {
  data: GptHistory[];
  limit?: number;
  more?: boolean;
  page?: number;
  total?: number;
}

export interface CreateGptHistoryBody {
  prompts?: GptHistoryPrompt[];
  title?: string;
}

export interface UpdateGptHistoryBody {
  prompts?: GptHistoryPrompt[];
  title?: string;
}

export interface GetGptHistoriesArgs {
  limit?: number;
  page?: number;
  sort?: string;
}

export const terrenoApi = openapi
  .enhanceEndpoints({addTagTypes: ["gptHistories", "profile"]})
  .injectEndpoints({
    endpoints: (builder) => ({
      deleteGptHistoriesById: builder.mutation<void, {id: string}>({
        invalidatesTags: (_result, _error, {id}) => [
          {id, type: "gptHistories" as const},
          {id: "LIST", type: "gptHistories" as const},
        ],
        query: ({id}) => ({
          method: "DELETE",
          url: `/gpt/histories/${id}`,
        }),
      }),
      // Selectable AI chat models (derived from backend config + Vertex enabled-model check)
      getAiModels: builder.query<AiModelsResponse, void>({
        query: () => ({
          method: "GET",
          url: "/ai/models",
        }),
      }),
      // AI Request Explorer (admin only)
      getAiRequestsExplorer: builder.query<
        AIRequestExplorerResponse,
        AIRequestExplorerParams | undefined
      >({
        query: (params) => ({
          method: "GET",
          params: params ?? {},
          url: "/aiRequestsExplorer",
        }),
      }),
      getGptHistories: builder.query<GptHistoriesListResponse, GetGptHistoriesArgs | undefined>({
        providesTags: (result) =>
          result?.data
            ? [
                ...result.data.map(({id}) => ({id, type: "gptHistories" as const})),
                {id: "LIST", type: "gptHistories" as const},
              ]
            : [{id: "LIST", type: "gptHistories" as const}],
        query: (args) => ({
          params: {
            limit: args?.limit,
            page: args?.page,
            sort: args?.sort,
          },
          url: "/gpt/histories",
        }),
      }),
      // The @terreno/rtk base query returns the `data` of single-document responses, so this
      // endpoint and the GptHistory mutations below resolve to the history itself.
      getGptHistoriesById: builder.query<GptHistory, {id: string}>({
        providesTags: (_result, _error, {id}) => [{id, type: "gptHistories" as const}],
        query: ({id}) => ({url: `/gpt/histories/${id}`}),
      }),
      // Get current user profile
      getMe: builder.query<ProfileResponse, void>({
        providesTags: ["profile"],
        query: () => ({
          method: "GET",
          url: "/auth/me",
        }),
      }),
      patchGptHistoriesById: builder.mutation<GptHistory, {body: UpdateGptHistoryBody; id: string}>(
        {
          invalidatesTags: (_result, _error, {id}) => [
            {id, type: "gptHistories" as const},
            {id: "LIST", type: "gptHistories" as const},
          ],
          query: ({body, id}) => ({
            body,
            method: "PATCH",
            url: `/gpt/histories/${id}`,
          }),
        }
      ),
      // Update current user profile
      patchMe: builder.mutation<ProfileResponse, UpdateProfileRequest>({
        invalidatesTags: ["profile"],
        query: (body) => ({
          body,
          method: "PATCH",
          url: "/auth/me",
        }),
      }),
      postAuthForgotPassword: builder.mutation<{ok: boolean}, {email: string}>({
        query: (body) => ({
          body,
          method: "POST",
          url: "/auth/forgotPassword",
        }),
      }),
      postAuthSendVerification: builder.mutation<{ok: boolean}, void>({
        invalidatesTags: ["profile"],
        query: () => ({
          method: "POST",
          url: "/auth/sendVerification",
        }),
      }),
      postAuthVerifyEmail: builder.mutation<{ok: boolean}, {token: string}>({
        invalidatesTags: ["profile"],
        query: (body) => ({
          body,
          method: "POST",
          url: "/auth/verifyEmail",
        }),
      }),
      postCommsDevTestPush: builder.mutation<
        {accepted: number; results: unknown[]; tokenCount: number},
        {body?: string; title?: string} | undefined
      >({
        query: (body) => ({
          body: body ?? {},
          method: "POST",
          url: "/comms/dev/testPush",
        }),
      }),
      postGptHistories: builder.mutation<GptHistory, {body: CreateGptHistoryBody}>({
        invalidatesTags: [{id: "LIST", type: "gptHistories"}],
        query: ({body}) => ({
          body,
          method: "POST",
          url: "/gpt/histories",
        }),
      }),
      postNotificationsDevNotify: builder.mutation<
        {notificationId: string},
        {body?: string; href?: string; kind?: string; title?: string} | undefined
      >({
        query: (body) => ({
          body: body ?? {},
          method: "POST",
          url: "/notifications/dev/notify",
        }),
      }),
      postNotificationsMarkAllRead: builder.mutation<{modified: number}, void>({
        query: () => ({
          method: "POST",
          url: "/notifications/mark-all-read",
        }),
      }),
      setAdminUserPassword: builder.mutation<
        {data: {_id: string; message: string}},
        SetAdminUserPasswordRequest
      >({
        invalidatesTags: ["users"],
        query: ({id, password}) => ({
          body: {password},
          method: "POST",
          url: `/users/${id}/password`,
        }),
      }),
    }),
    overrideExisting: true,
  })
  // Enhance endpoints is where we can add different tags to endpoints and more complex
  // invalidations.
  .enhanceEndpoints({
    addTagTypes: [
      "admin_scriptRuns",
      "admin_scriptTask",
      "consentForms",
      "feature-flags",
      "gptHistories",
      "profile",
      "PendingConsents",
    ],
    endpoints: {
      ...generateTags(openapi, [...CACHE_TAG_TYPES, "consentForms", "PendingConsents"]),
      ...TODO_REALTIME_ENDPOINTS,
    },
  });

export const {
  useDeleteGptHistoriesByIdMutation,
  useGetGptHistoriesQuery,
  useResetPasswordMutation,
  useGetMeQuery,
  usePatchGptHistoriesByIdMutation,
  usePatchMeMutation,
  usePostAuthForgotPasswordMutation,
  usePostAuthSendVerificationMutation,
  usePostAuthVerifyEmailMutation,
  usePostCommsDevTestPushMutation,
  usePostNotificationsDevNotifyMutation,
  useGetAiModelsQuery,
  useSetAdminUserPasswordMutation,
} = terrenoApi;
export * from "./openApiSdk";
