// This takes the autogenerated SDK and adds some extra functionality to it. For example,
// we can add extra tags to endpoints.

import {generateTags, realtimeDocument, realtimeList} from "@terreno/rtk";

import {
  addTagTypes,
  type GetGptHistoriesArgs,
  type GetGptHistoriesByIdRes,
  type GetGptHistoriesRes,
  openapi,
  type PatchGptHistoriesByIdArgs,
  type PostGptHistoriesArgs,
} from "./openApiSdk";

/** Tag types used by generateTags — todos are excluded; their cache is websocket-only. */
const CACHE_TAG_TYPES = addTagTypes.filter((tag) => tag !== "todos");

const TODO_REALTIME_ENDPOINTS = {
  deleteTodosById: {
    invalidatesTags: [] as const,
  },
  getTodos: {
    onCacheEntryAdded: realtimeList("todos"),
    providesTags: () => [] as const,
  },
  getTodosById: {
    onCacheEntryAdded: realtimeDocument("todos"),
    providesTags: () => [] as const,
  },
  patchTodosById: {
    invalidatesTags: [] as const,
  },
  postTodos: {
    invalidatesTags: [] as const,
  },
};

// This is where we can modify the SDK. For example,
// we can add a transformResponse to the endpoints or we can add extra tags. We can also add extra
// endpoints, since we don't automatically generate for endpoints that don't use the router
// currently.

// Profile response type — emptyApi's base query already unwraps the `data` envelope
export interface ProfileResponse {
  _id: string;
  id: string;
  email: string;
  name: string;
  admin?: boolean;
  emailVerified?: boolean;
  permissions?: Record<string, readonly string[]>;
  roles?: string[];
}

// AI Request Explorer types
interface AIRequestExplorerItem {
  _id: string;
  aiModel: string;
  created: string;
  error?: string;
  prompt: string;
  requestType: string;
  response?: string;
  responseTime?: number;
  tokensUsed?: number;
  user?: {email?: string; name?: string};
  userId?: string;
}

export interface AIRequestExplorerResponse {
  data: AIRequestExplorerItem[];
  limit: number;
  more: boolean;
  page: number;
  total: number;
}

export interface AIRequestExplorerParams {
  endDate?: string;
  limit?: number;
  page?: number;
  requestType?: string;
  startDate?: string;
}

// Selectable AI chat model option returned by GET /ai/models
interface AiModelOption {
  label: string;
  value: string;
}

export interface AiModelsResponse {
  models: AiModelOption[];
}

// Profile update request type
export interface UpdateProfileRequest {
  name?: string;
  email?: string;
  password?: string;
}

export interface SetAdminUserPasswordRequest {
  id: string;
  password: string;
}

// The generated GptHistory endpoints are overridden below to return `GptHistory`, which adds what
// the generated types cannot express: the `id` virtual, `prompts` the server always sends, the
// ask's input and card as objects, and the streaming reply's `status` and `streamId`. Their cache
// tags come from `generateTags` at the end, under the generated `gpthistories` tag, so generated
// mutations such as the headless `turn` action refresh them too.
type GeneratedPendingAsk = NonNullable<GetGptHistoriesByIdRes["pendingAsk"]>;
type GeneratedPrompt = NonNullable<GetGptHistoriesByIdRes["prompts"]>[number];

/** The ask a conversation is waiting on. Only the chat turn writes it, so clients never send it. */
interface GptHistoryPendingAsk extends Omit<GeneratedPendingAsk, "input" | "simple"> {
  input: Record<string, unknown>;
  simple: Record<string, unknown>;
}

interface GptHistoryPrompt extends GeneratedPrompt {
  /** "streaming" while /gpt/prompt is still writing this reply; resume via /gpt/histories/:id/stream. */
  status?: "streaming" | "complete" | "error";
  streamId?: string;
}

export interface GptHistory extends Omit<GetGptHistoriesByIdRes, "pendingAsk" | "prompts"> {
  id: string;
  pendingAsk?: GptHistoryPendingAsk;
  prompts: GptHistoryPrompt[];
}

interface GptHistoriesListResponse extends Omit<GetGptHistoriesRes, "data"> {
  data: GptHistory[];
}

/** The `data` of a POST /files/upload response. */
interface UploadedFileResponse {
  filename: string;
  gcsKey: string;
  id: string;
  mimeType: string;
  size: number;
  url: string;
}

export const terrenoApi = openapi
  .enhanceEndpoints({addTagTypes: ["profile"]})
  .injectEndpoints({
    endpoints: (builder) => ({
      deleteGptHistoriesById: builder.mutation<void, {id: string}>({
        query: ({id}) => ({
          method: "DELETE",
          url: `/gpt/histories/${id}`,
        }),
      }),
      // Selectable AI chat models (derived from backend config + Vertex enabled-model check)
      getAiModels: builder.query<AiModelsResponse, void>({
        query: () => ({
          method: "GET",
          url: "/ai/models",
        }),
      }),
      // AI Request Explorer (admin only)
      getAiRequestsExplorer: builder.query<
        AIRequestExplorerResponse,
        AIRequestExplorerParams | undefined
      >({
        query: (params) => ({
          method: "GET",
          params: params ?? {},
          url: "/aiRequestsExplorer",
        }),
      }),
      getGptHistories: builder.query<GptHistoriesListResponse, GetGptHistoriesArgs | undefined>({
        query: (args) => ({
          params: {
            limit: args?.limit,
            page: args?.page,
            sort: args?.sort,
          },
          url: "/gpt/histories",
        }),
      }),
      // The @terreno/rtk base query returns the `data` of single-document responses, so this
      // endpoint and the GptHistory mutations below resolve to the history itself.
      getGptHistoriesById: builder.query<GptHistory, {id: string}>({
        query: ({id}) => ({url: `/gpt/histories/${id}`}),
      }),
      // Get current user profile
      getMe: builder.query<ProfileResponse, void>({
        providesTags: ["profile"],
        query: () => ({
          method: "GET",
          url: "/auth/me",
        }),
      }),
      patchGptHistoriesById: builder.mutation<GptHistory, PatchGptHistoriesByIdArgs>({
        query: ({body, id}) => ({
          body,
          method: "PATCH",
          url: `/gpt/histories/${id}`,
        }),
      }),
      // Update current user profile
      patchMe: builder.mutation<ProfileResponse, UpdateProfileRequest>({
        invalidatesTags: ["profile"],
        query: (body) => ({
          body,
          method: "PATCH",
          url: "/auth/me",
        }),
      }),
      postAuthForgotPassword: builder.mutation<{ok: boolean}, {email: string}>({
        query: (body) => ({
          body,
          method: "POST",
          url: "/auth/forgotPassword",
        }),
      }),
      postAuthSendVerification: builder.mutation<{ok: boolean}, void>({
        invalidatesTags: ["profile"],
        query: () => ({
          method: "POST",
          url: "/auth/sendVerification",
        }),
      }),
      postAuthVerifyEmail: builder.mutation<{ok: boolean}, {token: string}>({
        invalidatesTags: ["profile"],
        query: (body) => ({
          body,
          method: "POST",
          url: "/auth/verifyEmail",
        }),
      }),
      postCommsDevTestPush: builder.mutation<
        {accepted: number; results: unknown[]; tokenCount: number},
        {body?: string; title?: string} | undefined
      >({
        query: (body) => ({
          body: body ?? {},
          method: "POST",
          url: "/comms/dev/testPush",
        }),
      }),
      // Hand-written: `/files/*` exists only on a server with a GCS bucket, so the generated SDK
      // has no file endpoints. The body is multipart form data with a `file` part; the base
      // query sends FormData as is, and the fetch sets its multipart boundary. A server without
      // the routes answers 404 in plain text, so parse by content type to keep that a 404.
      postFilesUpload: builder.mutation<UploadedFileResponse, FormData>({
        query: (body) => ({
          body,
          method: "POST",
          responseHandler: "content-type",
          url: "/files/upload",
        }),
        transformResponse: (response: {data: UploadedFileResponse}) => response.data,
      }),
      postGptHistories: builder.mutation<GptHistory, {body: PostGptHistoriesArgs}>({
        invalidatesTags: ["gpthistories"],
        query: ({body}) => ({
          body,
          method: "POST",
          url: "/gpt/histories",
        }),
      }),
      postNotificationsDevNotify: builder.mutation<
        {notificationId: string},
        {body?: string; href?: string; kind?: string; title?: string} | undefined
      >({
        query: (body) => ({
          body: body ?? {},
          method: "POST",
          url: "/notifications/dev/notify",
        }),
      }),
      postNotificationsMarkAllRead: builder.mutation<{modified: number}, void>({
        query: () => ({
          method: "POST",
          url: "/notifications/mark-all-read",
        }),
      }),
      setAdminUserPassword: builder.mutation<
        {data: {_id: string; message: string}},
        SetAdminUserPasswordRequest
      >({
        invalidatesTags: ["users"],
        query: ({id, password}) => ({
          body: {password},
          method: "POST",
          url: `/users/${id}/password`,
        }),
      }),
    }),
    overrideExisting: true,
  })
  // Enhance endpoints is where we can add different tags to endpoints and more complex
  // invalidations.
  .enhanceEndpoints({
    addTagTypes: [
      "admin_scriptRuns",
      "admin_scriptTask",
      "consentForms",
      "feature-flags",
      "profile",
      "PendingConsents",
    ],
    endpoints: {
      ...generateTags(openapi, [...CACHE_TAG_TYPES, "consentForms", "PendingConsents"]),
      ...TODO_REALTIME_ENDPOINTS,
    },
  });

export const {
  useDeleteGptHistoriesByIdMutation,
  useGetGptHistoriesQuery,
  useResetPasswordMutation,
  useGetMeQuery,
  usePatchGptHistoriesByIdMutation,
  usePatchMeMutation,
  usePostAuthForgotPasswordMutation,
  usePostAuthSendVerificationMutation,
  usePostAuthVerifyEmailMutation,
  usePostCommsDevTestPushMutation,
  usePostFilesUploadMutation,
  usePostNotificationsDevNotifyMutation,
  useGetAiModelsQuery,
  useSetAdminUserPasswordMutation,
} = terrenoApi;
export * from "./openApiSdk";
