// GENERATED by @terreno/syncdb (terreno-syncdb-codegen). Do not edit.
// Friendly names (useTodos / useTodo / useCreateTodo / …) so this file can
// coexist with RTK openApiSdk.ts. Mutation triggers are synchronous
// ({mutationId, id}) — there is no .unwrap() or per-call isLoading.

import {createCollectionHooks} from "@terreno/syncdb/react";

export interface Todo {
  _id: string;
  completed?: boolean;
  ownerId: string;
  priority?: "low" | "medium" | "high";
  tags?: string[];
  title: string;
  updated: string;
  created: string;
  deleted?: boolean;
  _syncPrevStream?: string;
  _syncSeq?: number;
}

export interface CreateTodoBody {
  _id?: string;
  completed?: boolean;
  ownerId?: string;
  priority?: "low" | "medium" | "high";
  tags?: string[];
  title?: string;
  updated?: string;
  created?: string;
  deleted?: boolean;
  _syncPrevStream?: string;
  _syncSeq?: number;
}

export interface UpdateTodoBody {
  _id?: string;
  completed?: boolean;
  ownerId?: string;
  priority?: "low" | "medium" | "high";
  tags?: string[];
  title?: string;
  updated?: string;
  created?: string;
  deleted?: boolean;
  _syncPrevStream?: string;
  _syncSeq?: number;
}

export interface Notification {
  _id: string;
  archivedAt?: string;
  body: string;
  href?: string;
  kind?: string;
  ownerId: string;
  readAt?: string;
  title: string;
  updated: string;
  created: string;
  deleted?: boolean;
  _syncPrevStream?: string;
  _syncSeq?: number;
}

export type CreateNotificationBody = {};

export interface UpdateNotificationBody {
  _id?: string;
  archivedAt?: string;
  body?: string;
  href?: string;
  kind?: string;
  ownerId?: string;
  readAt?: string;
  title?: string;
  updated?: string;
  created?: string;
  deleted?: boolean;
  _syncPrevStream?: string;
  _syncSeq?: number;
}

export interface NotificationPreference {
  _id: string;
  inapp?: boolean;
  mail?: boolean;
  ownerId: string;
  push?: boolean;
  sms?: boolean;
  updated: string;
  created: string;
  deleted?: boolean;
  _syncPrevStream?: string;
  _syncSeq?: number;
}

export interface CreateNotificationPreferenceBody {
  _id?: string;
  inapp?: boolean;
  mail?: boolean;
  ownerId?: string;
  push?: boolean;
  sms?: boolean;
  updated?: string;
  created?: string;
  deleted?: boolean;
  _syncPrevStream?: string;
  _syncSeq?: number;
}

export interface UpdateNotificationPreferenceBody {
  _id?: string;
  inapp?: boolean;
  mail?: boolean;
  ownerId?: string;
  push?: boolean;
  sms?: boolean;
  updated?: string;
  created?: string;
  deleted?: boolean;
  _syncPrevStream?: string;
  _syncSeq?: number;
}

/** Collections with sync enabled on the backend; pass to createSyncDb. */
export const SYNC_COLLECTIONS = ["todos", "notifications", "notification-preferences"] as const;

export const {
  useListQuery: useTodos,
  useReadQuery: useTodo,
  useCreateMutation: useCreateTodo,
  useUpdateMutation: useUpdateTodo,
  useDeleteMutation: useDeleteTodo,
  useWindowQuery: useTodosWindow,
} = createCollectionHooks<Todo, CreateTodoBody, UpdateTodoBody>({
  collection: "todos",
  retries: false,
});

export const {
  useListQuery: useNotifications,
  useReadQuery: useNotification,
  useCreateMutation: useCreateNotification,
  useUpdateMutation: useUpdateNotification,
  useDeleteMutation: useDeleteNotification,
  useWindowQuery: useNotificationsWindow,
} = createCollectionHooks<Notification, CreateNotificationBody, UpdateNotificationBody>({
  collection: "notifications",
});

export const {
  useListQuery: useNotificationPreferences,
  useReadQuery: useNotificationPreference,
  useCreateMutation: useCreateNotificationPreference,
  useUpdateMutation: useUpdateNotificationPreference,
  useDeleteMutation: useDeleteNotificationPreference,
  useWindowQuery: useNotificationPreferencesWindow,
} = createCollectionHooks<
  NotificationPreference,
  CreateNotificationPreferenceBody,
  UpdateNotificationPreferenceBody
>({collection: "notification-preferences"});
