import packageJson from "../package.json" with {type: "json"};

/** Pinned so `npx -y` does not resolve a moving `@latest` target in generated MCP configs. */
export const PLAYWRIGHT_MCP_PACKAGE_VERSION = "0.0.76";

/** Bun-safe Mongo stack — caret ranges resolve to mongoose 9.10 / mongodb 7.6 / bson 7.3 and crash Bun. */
export const MONGOOSE_VERSION = "9.7.4";
export const MONGODB_VERSION = "7.2.0";
export const BSON_VERSION = "7.2.0";

export const PACKAGE_VERSION = packageJson.version;
const TERRENO_DEP_VERSION = `^${PACKAGE_VERSION}`;

export interface BootstrapArgs {
  appName: string;
  appDisplayName: string;
  description?: string;
  mcpServerUrl?: string;
}

export interface GeneratedFile {
  path: string;
  content: string;
}

const generateCursorRules = (args: BootstrapArgs): string => {
  const {appDisplayName} = args;
  return `# ${appDisplayName}

A full-stack application built with the Terreno framework.

## Project Structure

- **frontend/** - Expo/React Native frontend using @terreno/ui, @terreno/syncdb, and @terreno/rtk (SDK + Better Auth)
- **backend/** - Express/Mongoose backend using @terreno/api

## Development

Uses [Bun](https://bun.sh/) as the package manager.

\`\`\`bash
# Backend
cd backend && bun run dev    # Start backend on port 4000

# Frontend
cd frontend && bun run web   # Start web frontend
cd frontend && bun run sdk   # Regenerate SDK after backend changes
\`\`\`

## Code Style

### TypeScript/JavaScript
- Use ES module syntax and TypeScript for all code
- Prefer interfaces over types; avoid enums, use maps
- Prefer const arrow functions over \`function\` keyword
- Use descriptive variable names with auxiliary verbs (e.g., \`isLoading\`)
- Favor named exports
- Use the RORO pattern (Receive an Object, Return an Object)

### Dates and Time
- Always use Luxon instead of Date or dayjs

### Error Handling
- Check error conditions at start of functions and return early
- Limit nested if statements
- Use multiline syntax with curly braces for all conditionals

### React Best Practices
- Use functional components with \`React.FC\` type
- Add explanatory comment above each \`useEffect\`
- Wrap callbacks in \`useCallback\`
- Use Redux Toolkit for state management

### Backend Conventions
- Use \`modelRouter\` for CRUD endpoints
- Use \`APIError\` for error responses
- Use \`logger.info/warn/error/debug\` for logging
- Use \`Model.findExactlyOne\` or \`Model.findOneOrNone\` (not \`Model.findOne\`)

### Frontend Conventions
- Use \`@terreno/syncdb/react\` hooks (\`useQuery\`, \`useMutate\`) for synced collection CRUD
- Use generated SDK hooks from \`@/store/openApiSdk\` for non-synced routes only
- Use @terreno/ui components (Box, Page, Button, TextField, etc.)
- Never modify \`openApiSdk.ts\` manually - regenerate with \`bun run sdk\`

## AI Assistance

This project is configured to use the Terreno MCP server for AI-assisted development.
Use the MCP tools and prompts for:
- Generating new models and routes
- Creating screens and forms
- Following Terreno patterns and best practices
`;
};

const generateMcpSettings = (args: BootstrapArgs): string => {
  const mcpUrl = args.mcpServerUrl || "https://mcp.terreno.app";
  return JSON.stringify(
    {
      mcpServers: {
        expo: {
          type: "http",
          url: "https://mcp.expo.dev/mcp",
        },
        playwright: {
          args: ["-y", `@playwright/mcp@${PLAYWRIGHT_MCP_PACKAGE_VERSION}`],
          command: "npx",
        },
        terreno: {
          type: "http",
          url: `${mcpUrl}/mcp`,
        },
        "terreno-local": {
          args: ["terreno-mcp-local"],
          command: "bunx",
        },
      },
    },
    null,
    2
  );
};

const generateRootGitignore = (): string => {
  return [
    "# Dependencies",
    "node_modules/",
    "",
    "# Local env (use .env.example as a template)",
    "backend/.env",
    "frontend/.env",
    "",
    "# Local Terreno dev logs (winston JSONL + optional browser fallback)",
    ".terreno/",
    "",
    "# Build outputs",
    "dist/",
    "build/",
    "",
    "# OS",
    ".DS_Store",
    "",
  ].join("\n");
};

const DEPLOYMENT_BASELINE_DOC =
  "https://github.com/TerrenoLabs/terreno/blob/master/docs/explanation/deployment-baseline.md";
const DEPLOY_BACKEND_CLOUD_RUN_DOC =
  "https://github.com/TerrenoLabs/terreno/blob/master/docs/how-to/deploy-backend-to-cloud-run.md";
const BUILD_FOR_WEB_DOC =
  "https://github.com/TerrenoLabs/terreno/blob/master/docs/how-to/build-for-web.md";

const generateRootReadme = (args: BootstrapArgs): string => {
  const {appDisplayName, appName} = args;
  const dbName = appName.replace(/-/g, "_");
  return `# ${appDisplayName}

Full-stack Terreno app generated by [\`create-terreno-app\`](https://www.npmjs.com/package/create-terreno-app).

## Project structure

- **backend/** — Express/Mongoose API (\`@terreno/api\`, Better Auth, admin, sync)
- **frontend/** — Expo universal app (\`@terreno/ui\`, \`@terreno/syncdb\`, \`@terreno/rtk\`)

## Local development

1. **MongoDB replica set** (required for sync/realtime). For local dev, run a single-node replica set and point \`MONGO_URI\` at it. See the [deployment baseline](${DEPLOYMENT_BASELINE_DOC}).

2. **Install dependencies**

\`\`\`bash
cd backend && bun install
cd ../frontend && bun install
\`\`\`

3. **Configure env** — copy \`backend/.env.example\` and \`frontend/.env.example\` to \`.env\` (or use the generated, gitignored local defaults in \`backend/.env\` / \`frontend/.env\`).

4. **Seed login users**

\`\`\`bash
cd backend && bun run seed
\`\`\`

Creates \`test@example.com\` and \`admin@example.com\` (password \`testpassword123\`).

5. **Start the stack**

\`\`\`bash
# Terminal 1 — API (default port 4000)
cd backend && bun run dev

# Terminal 2 — web UI (port 8082)
cd frontend && bun run web
\`\`\`

After backend route changes, regenerate the OpenAPI SDK:

\`\`\`bash
cd frontend && bun run sdk
\`\`\`

## Deploy

Read the [deployment baseline](${DEPLOYMENT_BASELINE_DOC}) first (MongoDB replica set, auth secrets, \`EXPO_PUBLIC_*\` at build time, \`/health\`, and more).

### Backend (Docker / Cloud Run)

This repo includes a **consumer** \`Dockerfile\` at the project root. It builds only \`backend/\` — not the Terreno monorepo.

\`\`\`bash
docker build -t ${appName}-backend .
docker run --rm -p 8080:8080 \\
  -e MONGO_URI='mongodb+srv://...' \\
  -e BETTER_AUTH_SECRET='...' \\
  -e BETTER_AUTH_URL='https://api.example.com' \\
  ${appName}-backend
\`\`\`

Cloud Run and other platforms set \`PORT\`; the server listens on that port and exposes \`GET /health\`.

Step-by-step GCP deploy: [Deploy backend to Cloud Run](${DEPLOY_BACKEND_CLOUD_RUN_DOC}).

### Frontend (static web)

Set \`EXPO_PUBLIC_API_URL\` **before** export — it is inlined into the bundle at build time:

\`\`\`bash
cd frontend
EXPO_PUBLIC_API_URL=https://api.example.com bun expo export --platform web
\`\`\`

Full walkthrough: [Build for web](${BUILD_FOR_WEB_DOC}).

## Default local database name

\`MONGO_URI\` defaults to \`mongodb://127.0.0.1:27017/${dbName}?replicaSet=rs0\` in \`backend/.env\`.
`;
};

const generateRootDockerfile = (): string => {
  return `# Consumer Terreno backend image — builds backend/ only (not the Terreno monorepo).
FROM oven/bun:1-slim AS builder
WORKDIR /app

COPY backend/package.json ./
RUN bun install

COPY backend/ ./

FROM oven/bun:1-slim
WORKDIR /app

RUN apt-get update \\
  && apt-get install -y --no-install-recommends curl \\
  && rm -rf /var/lib/apt/lists/* \\
  && useradd -r -u 1001 appuser

COPY --from=builder /app/ ./

ENV NODE_ENV=production
ENV PORT=8080

EXPOSE 8080

HEALTHCHECK --interval=30s --timeout=5s --start-period=40s --retries=3 \\
  CMD curl -fsS "http://127.0.0.1:\${PORT}/health" | grep -q '"healthy":true' || exit 1

RUN chown -R appuser:appuser /app
USER appuser

CMD ["bun", "run", "start"]
`;
};

const generateRootDockerignore = (): string => {
  return [
    ".git",
    ".gitignore",
    "**/node_modules",
    "**/dist",
    "backend/.env",
    "frontend/.env",
    "",
  ].join("\n");
};

const generateClaudeMd = (args: BootstrapArgs): string => {
  const {appDisplayName} = args;
  return `# ${appDisplayName}

A full-stack application built with the Terreno framework.

## Project Structure

- **frontend/** - Expo/React Native frontend
- **backend/** - Express/Mongoose backend

## Development

\`\`\`bash
# Install dependencies
cd backend && bun install
cd frontend && bun install

# Start backend (port 4000)
cd backend && bun run dev

# Start frontend (port 8082)
cd frontend && bun run web

# Regenerate SDK after backend changes
cd frontend && bun run sdk
\`\`\`

## Adding Features

1. Create model in \`backend/src/models/\`
2. Create route in \`backend/src/api/\`
3. Register route in \`backend/src/server.ts\`
4. Regenerate SDK: \`cd frontend && bun run sdk\`
5. Create screens in \`frontend/app/\`

## Code Style

- Use TypeScript with ES modules
- Use Luxon for dates
- Prefer const arrow functions
- Named exports preferred
- Use interfaces over types
`;
};

// Backend file generators
const generateBackendPackageJson = (args: BootstrapArgs): string => {
  const {appName} = args;
  return JSON.stringify(
    {
      dependencies: {
        "@terreno/admin-backend": TERRENO_DEP_VERSION,
        "@terreno/api": TERRENO_DEP_VERSION,
        "@terreno/api-health": TERRENO_DEP_VERSION,
        luxon: "^3.7.2",
        mongodb: MONGODB_VERSION,
        mongoose: MONGOOSE_VERSION,
        "passport-local-mongoose": "^9.0.1",
      },
      devDependencies: {
        "@biomejs/biome": "^2.3.6",
        "@types/bun": "^1.4.0",
        "@types/express": "^4.17.21",
        "@types/luxon": "^3.7.1",
        typescript: "~6.0.3",
      },
      name: `@${appName}/backend`,
      overrides: {
        bson: BSON_VERSION,
        mongodb: MONGODB_VERSION,
      },
      private: true,
      scripts: {
        build: "bun build src/index.ts --outdir ./dist --target node",
        compile: "tsc",
        dev: "PORT=4000 bun run --watch src/index.ts",
        format: "biome format --write .",
        lint: "biome check .",
        "lint:fix": "biome check --write .",
        "lint:unsafefix": "biome check --write . --unsafe",
        seed: "bun run src/scripts/seed.ts",
        start: "bun run src/index.ts",
        test: "bun test",
      },
      type: "module",
      version: "1.0.0",
    },
    null,
    2
  );
};

const generateBackendTsConfig = (): string => {
  return JSON.stringify(
    {
      compilerOptions: {
        lib: ["esnext"],
        module: "preserve",
        moduleDetection: "force",
        noEmit: true,
        skipLibCheck: true,
        strict: true,
        target: "esnext",
        types: ["bun"],
        verbatimModuleSyntax: true,
      },
      exclude: ["node_modules", "dist"],
      include: ["src"],
    },
    null,
    2
  );
};

const generateBackendBiomeJsonc = (): string => {
  return `{
  "$schema": "./node_modules/@biomejs/biome/configuration_schema.json",
  "assist": {
    "actions": {
      "source": {
        "organizeImports": "on",
        "useSortedAttributes": "on",
        "useSortedKeys": "on"
      }
    },
    "enabled": true
  },
  "files": {
    "includes": [
      "package.json",
      "src/**/*.ts",
      "src/**/*.tsx",
      "!!**/node_modules",
      "!!**/dist",
      "!!**/build",
      "!!**/coverage",
      "!!**/.git"
    ]
  },
  "formatter": {
    "enabled": true,
    "indentStyle": "space",
    "indentWidth": 2,
    "lineWidth": 100
  },
  "javascript": {
    "formatter": {
      "arrowParentheses": "always",
      "bracketSpacing": false,
      "jsxQuoteStyle": "double",
      "quoteStyle": "double",
      "semicolons": "always",
      "trailingCommas": "es5"
    },
    // TODO: Remove once we don't need to import React from 'react' in our JSX files.
    "jsxRuntime": "reactClassic"
  },
  "linter": {
    "enabled": true,
    "rules": {
      "nursery": {
        "noFloatingPromises": "error",
        "noMisusedPromises": "error",
        "useExhaustiveSwitchCases": "error"
      },
      "recommended": true,
      "suspicious": {
        "noConsole": {
          "level": "error",
          "options": {
            "allow": ["assert", "debug", "error", "info", "warn"]
          }
        },
        "noExplicitAny": "off",
        "noImplicitAnyLet": "off"
      }
    }
  },
  "vcs": {
    "clientKind": "git",
    "defaultBranch": "master",
    "enabled": true
  }
}
`;
};

const generateBackendIndex = (): string => {
  return `import "./server";
`;
};

const generateBackendAccess = (): string => {
  return `import {
  createAccess,
  terrenoStatements,
  type UserModel as TerrenoAuthUserModel,
} from "@terreno/api";
import mongoose from "mongoose";

import {User} from "./models/user";

export const access = createAccess({
  connection: mongoose.connection,
  organizations: true,
  statements: terrenoStatements,
  userModel: User as unknown as TerrenoAuthUserModel,
});
`;
};

const generateBackendServer = (args: BootstrapArgs): string => {
  const {appDisplayName} = args;
  return `import {AdminApp} from "@terreno/admin-backend";
import {HealthApp} from "@terreno/api-health";
import {
  BetterAuthApp,
  checkModelsStrict,
  createBetterAuth,
  getMongoClientFromMongoose,
  logger,
  Membership,
  RealtimeApp,
  SyncApp,
  TerrenoApp,
  type UserModel as TerrenoAuthUserModel,
} from "@terreno/api";
import type express from "express";
import mongoose from "mongoose";
import {access} from "./access";
import {userRouter} from "./api/users";
import {AppConfiguration} from "./models/appConfiguration";
import {organizationSettingsSchema} from "./models/organizationSettings";
import {User} from "./models/user";
import "./types/models/organizationSettingsTypes";
import {buildBetterAuthConfig, getWebOrigins} from "./utils/betterAuthConfig";
import {connectToMongoDB} from "./utils/database";

const isDeployed = process.env.NODE_ENV === "production";

export const start = async (skipListen = false): Promise<express.Application> => {
  await connectToMongoDB();

  logger.info(\`Starting ${appDisplayName} server on port \${process.env.PORT || 4000}\`);

  if (!isDeployed) {
    checkModelsStrict();
  }

  await access.roles.seedDefaults();

  const betterAuthConfig = buildBetterAuthConfig();
  const betterAuthInstance = betterAuthConfig
    ? createBetterAuth({
        config: betterAuthConfig,
        mongoClient: getMongoClientFromMongoose(),
        // noExplicitAny: User model type mismatch
        // biome-ignore lint/suspicious/noExplicitAny: User model type mismatch
        userModel: User as any,
      })
    : undefined;

  const terraApp = new TerrenoApp({
    accessControl: access,
    corsOrigin: getWebOrigins(),
    loggingOptions: {
      disableConsoleColors: isDeployed,
      level: "debug",
      logRequests: !isDeployed,
    },
    organizations: {
      settingsSchema: organizationSettingsSchema,
    },
    skipListen,
    // noExplicitAny: User model type mismatch
    // biome-ignore lint/suspicious/noExplicitAny: User model type mismatch
    userModel: User as any,
  }).configure(AppConfiguration);

  if (betterAuthConfig) {
    terraApp.register(
      new BetterAuthApp({
        config: betterAuthConfig,
        userModel: User as unknown as TerrenoAuthUserModel,
      })
    );
  }

  return terraApp
    .register(userRouter)
    .register(
      new HealthApp({
        check: async () => {
          const mongoConnected = mongoose.connection.readyState === 1;
          return {
            details: {
              database: mongoConnected ? "connected" : "disconnected",
              uptime: process.uptime(),
            },
            healthy: mongoConnected,
          };
        },
      })
    )
    .register(
      new AdminApp({
        models: [
          {
            displayName: "Users",
            listFields: ["email", "name", "admin", "created"],
            // noExplicitAny: User model type mismatch
            // biome-ignore lint/suspicious/noExplicitAny: User model type mismatch
            model: User as any,
            routePath: "/users",
          },
        ],
      })
    )
    .register(
      new SyncApp({
        accessControl: access,
        getUserScopes: async (user) => {
          const memberships = await Membership.findActiveForUser(user.id);
          return memberships.map((membership) => String(membership.organizationId));
        },
      })
    )
    .register(
      new RealtimeApp({
        betterAuth: betterAuthInstance
          ? {
              auth: betterAuthInstance,
              // noExplicitAny: User model type mismatch
              // biome-ignore lint/suspicious/noExplicitAny: User model type mismatch
              userModel: User as any,
            }
          : undefined,
        // noExplicitAny: User model type mismatch
        // biome-ignore lint/suspicious/noExplicitAny: User model type mismatch
        userModel: User as any,
      })
    )
    .start();
};

start().catch((error) => {
  logger.error(\`Fatal error starting server: \${error}\`);
});
`;
};

const generateBackendDatabase = (args: BootstrapArgs): string => {
  const {appName} = args;
  const dbName = appName.replace(/-/g, "_");
  return `import {logger} from "@terreno/api";
import mongoose from "mongoose";

export const connectToMongoDB = async (): Promise<void> => {
  if (mongoose.connection.readyState === 1) {
    logger.info("Already connected to MongoDB");
    return;
  }

  const mongoURI =
    process.env.MONGO_URI || "mongodb://127.0.0.1:27017/${dbName}?replicaSet=rs0";

  try {
    await mongoose.connect(mongoURI);
    logger.info("Connected to MongoDB");
  } catch (error: unknown) {
    logger.error(\`MongoDB connection error: \${error}\`);
    throw error;
  }

  mongoose.connection.on("error", (error: unknown) => {
    logger.error(\`MongoDB connection error: \${error}\`);
  });

  mongoose.connection.on("disconnected", () => {
    logger.warn("MongoDB disconnected");
  });
};
`;
};

const generateBackendSeed = (args: BootstrapArgs): string => {
  const {appDisplayName} = args;
  return `import {
  APIError,
  createBetterAuth,
  getMongoClientFromMongoose,
  logger,
  Membership,
  Organization,
  runSeedCli,
  seedBetterAuthUser,
  type SeedStep,
  type UserModel as TerrenoAuthUserModel,
} from "@terreno/api";
import mongoose from "mongoose";

import {access} from "../access";
import {User} from "../models/user";
import {buildBetterAuthConfig} from "../utils/betterAuthConfig";
import {connectToMongoDB} from "../utils/database";

const SEED_USERS = [
  {
    admin: false,
    email: "test@example.com",
    name: "Test User",
    password: "testpassword123",
  },
  {
    admin: true,
    email: "admin@example.com",
    name: "Admin User",
    password: "testpassword123",
  },
];

const seedSteps: SeedStep[] = [
  {
    description: "Create login-ready development users and reconcile profile fields",
    name: "users",
    run: async (context) => {
      if (context.dryRun) {
        for (const user of SEED_USERS) {
          const existing = await User.findByEmail(user.email);
          context.changes.push({
            change: existing ? "updated" : "created",
            count: 1,
            key: JSON.stringify({email: user.email}),
            model: User.modelName,
          });
        }
        return;
      }

      const config = buildBetterAuthConfig();
      if (!config) {
        throw new APIError({
          status: 500,
          title: "Seed users require Better Auth to be enabled",
        });
      }
      const auth = createBetterAuth({
        config,
        mongoClient: getMongoClientFromMongoose(),
        userModel: User as unknown as TerrenoAuthUserModel,
      });
      for (const definition of SEED_USERS) {
        const user = await seedBetterAuthUser({
          auth,
          user: definition,
          userModel: User as unknown as TerrenoAuthUserModel,
        });
        const appUser = user as unknown as {
          admin: boolean;
          save: () => Promise<unknown>;
        };
        appUser.admin = definition.admin;
        const roles = (appUser as unknown as {roles?: string[]}).roles ?? [];
        if (definition.admin && !roles.includes("operator")) {
          (appUser as unknown as {roles: string[]}).roles = [...roles, "operator"];
        }
        await appUser.save();
      }
    },
  },
  {
    description: "Create the default organization and attach the admin as org-admin",
    name: "organization",
    run: async (context) => {
      await access.roles.seedDefaults();
      const existing = await Organization.findOneOrNone({name: "${appDisplayName}"});
      if (context.dryRun) {
        context.changes.push({
          change: existing ? "updated" : "created",
          count: 1,
          key: JSON.stringify({name: "${appDisplayName}"}),
          model: Organization.modelName,
        });
        return;
      }
      const admin = await User.findByEmail("admin@example.com");
      if (!admin) {
        throw new APIError({
          status: 500,
          title: "Default organization requires admin@example.com",
        });
      }
      const organization =
        existing ??
        (await Organization.create({
          name: "${appDisplayName}",
          ownerId: admin._id,
        }));
      const membership = await Membership.findOneOrNone({
        organizationId: organization._id,
        userId: admin._id,
      });
      if (!membership) {
        await Membership.create({
          organizationId: organization._id,
          roleName: "org-admin",
          userId: admin._id,
        });
      }
    },
  },
];

const main = async (): Promise<void> => {
  const cli = await runSeedCli({
    allowProductionReset: () => process.env.ALLOW_SEED_RESET === "true",
    connect: connectToMongoDB,
    disconnect: async () => {
      await mongoose.disconnect();
    },
    name: "bun run seed",
    steps: seedSteps,
  });
  if (cli.help) {
    logger.info(cli.help);
  }
  process.exit(cli.exitCode);
};

main().catch((error: unknown) => {
  logger.error(\`Seed failed: \${error}\`);
  process.exit(1);
});
`;
};

const generateBackendBetterAuthConfig = (args: BootstrapArgs): string => {
  const {appName} = args;
  return `import type {AuthProvider, BetterAuthConfig} from "@terreno/api";

const DEFAULT_BETTER_AUTH_URL = "http://localhost:4000";
const DEFAULT_WEB_ORIGINS = ["http://localhost:8082", "http://127.0.0.1:8082"];
const APP_SCHEMES = ["${appName}://", "exp://"];

export const getAuthProvider = (): AuthProvider => {
  const provider = process.env.AUTH_PROVIDER as AuthProvider | undefined;
  return provider ?? "better-auth";
};

export const getWebOrigins = (): string[] => {
  const origins = new Set<string>(DEFAULT_WEB_ORIGINS);
  const fromEnv = process.env.CORS_ORIGINS?.split(",")
    .map((value) => value.trim())
    .filter(Boolean);
  for (const origin of fromEnv ?? []) {
    origins.add(origin);
  }
  return [...origins];
};

export const buildBetterAuthConfig = (): BetterAuthConfig | undefined => {
  if (getAuthProvider() !== "better-auth") {
    return undefined;
  }

  const secret = process.env.BETTER_AUTH_SECRET;
  if (!secret) {
    throw new Error("BETTER_AUTH_SECRET is required when AUTH_PROVIDER=better-auth");
  }

  return {
    baseURL: process.env.BETTER_AUTH_URL ?? DEFAULT_BETTER_AUTH_URL,
    crossDomainCookies: process.env.CROSS_DOMAIN_AUTH_COOKIES === "true",
    enabled: true,
    secret,
    trustedOrigins: [...APP_SCHEMES, ...getWebOrigins()],
  };
};
`;
};

const generateBackendModelPlugins = (): string => {
  return `import {
  createdUpdatedPlugin,
  findExactlyOne,
  findOneOrNone,
  isDeletedPlugin,
} from "@terreno/api";
import type mongoose from "mongoose";

// noExplicitAny: Leaving open for flexibility
// biome-ignore lint/suspicious/noExplicitAny: Leaving open for flexibility
export function addDefaultPlugins(schema: mongoose.Schema<any, any, any, any>): void {
  schema.plugin(createdUpdatedPlugin);
  schema.plugin(isDeletedPlugin);
  schema.plugin(findOneOrNone);
  schema.plugin(findExactlyOne);
}
`;
};

const generateBackendUserModel = (): string => {
  return `import mongoose from "mongoose";
import passportLocalMongoose from "passport-local-mongoose";
import type {UserDocument, UserModel} from "../types";
import {addDefaultPlugins} from "./modelPlugins";

const userSchema = new mongoose.Schema<UserDocument, UserModel>(
  {
    admin: {
      default: false,
      description: "Whether the user has administrator access",
      type: Boolean,
    },
    betterAuthId: {
      description: "Identifier linking to the Better Auth session provider",
      index: true,
      sparse: true,
      type: String,
    },
    email: {
      description: "The user's email address, used for authentication",
      lowercase: true,
      required: true,
      trim: true,
      type: String,
      unique: true,
    },
    name: {
      description: "The user's display name",
      required: true,
      trim: true,
      type: String,
    },
  },
  {strict: "throw", toJSON: {virtuals: true}, toObject: {virtuals: true}}
);

userSchema.plugin(passportLocalMongoose, {
  usernameField: "email",
});

addDefaultPlugins(userSchema);

userSchema.method("getDisplayName", function (this: UserDocument): string {
  return this.name;
});

export const User = mongoose.model<UserDocument, UserModel>("User", userSchema);

User.findByEmail = async function (email: string): Promise<UserDocument | null> {
  return this.findOneOrNone({email: email.toLowerCase()});
};
`;
};

const generateBackendAppConfiguration = (args: BootstrapArgs): string => {
  const {appDisplayName} = args;
  return `import {configurationPlugin, createdUpdatedPlugin} from "@terreno/api";
import mongoose, {Schema} from "mongoose";

const generalSchema = new Schema(
  {
    appName: {
      default: "${appDisplayName}",
      description: "Display name of the application",
      type: String,
    },
    maintenanceMode: {
      default: false,
      description: "When enabled, the app returns 503 for all non-admin requests",
      type: Boolean,
    },
  },
  {_id: false}
);

const debugSchema = new Schema(
  {
    websocketsDebug: {
      default: false,
      description: "Enable verbose WebSocket and realtime sync debug logging",
      type: Boolean,
    },
  },
  {_id: false}
);

export interface AppConfigDocument {
  general: {
    appName: string;
    maintenanceMode: boolean;
  };
  debug: {
    websocketsDebug: boolean;
  };
}

const appConfigSchema = new Schema<AppConfigDocument>(
  {
    general: {
      description: "General application settings",
      type: generalSchema,
    },
    debug: {
      description: "Debug and diagnostic settings",
      type: debugSchema,
    },
  },
  {strict: "throw", toJSON: {virtuals: true}, toObject: {virtuals: true}}
);

appConfigSchema.plugin(configurationPlugin);
appConfigSchema.plugin(createdUpdatedPlugin);

export const AppConfiguration = mongoose.model<AppConfigDocument>(
  "AppConfiguration",
  appConfigSchema
);
`;
};

const generateBackendOrganizationSettings = (): string => {
  return `import {createOrganizationSettingsSchema} from "@terreno/api";

export const organizationSettingsSchema = createOrganizationSettingsSchema({
  timezone: {
    description: "IANA timezone used for organization-local dates",
    type: String,
  },
});
`;
};

const generateBackendOrganizationSettingsTypes = (): string => {
  return `export interface AppOrganizationSettings {
  timezone?: string;
}

declare module "@terreno/api" {
  interface OrganizationSettings extends AppOrganizationSettings {}
}
`;
};

const generateBackendModelsIndex = (): string => {
  return `export * from "./appConfiguration";
export * from "./organizationSettings";
export * from "./user";
`;
};

const generateBackendUserRoutes = (): string => {
  return `import {Permissions, modelRouter} from "@terreno/api";
import type {Model} from "mongoose";
import {User} from "../models/user";
import type {UserDocument} from "../types";

export const userRouter = modelRouter("/users", User as unknown as Model<UserDocument>, {
  permissions: {
    create: [Permissions.IsAdmin],
    delete: [Permissions.IsAdmin],
    list: [Permissions.IsAdmin],
    read: [Permissions.IsAdmin],
    update: [Permissions.IsAdmin],
  },
  queryFields: ["email", "name"],
  sort: "name",
});
`;
};

const generateBackendTypes = (): string => {
  return `export * from "./models";
`;
};

const generateBackendTypesModels = (): string => {
  return `export * from "./organizationSettingsTypes";
export * from "./userTypes";
`;
};

const generateBackendUserTypes = (): string => {
  return `import type {APIErrorConstructor} from "@terreno/api";
import type mongoose from "mongoose";
import type {Document, Model} from "mongoose";
import type {
  PassportLocalMongooseDocument,
  PassportLocalMongooseModel,
} from "passport-local-mongoose";

type ModelQuery<T> = Partial<Record<keyof T, unknown>> & Record<string, unknown>;

export interface DefaultStatics<T> {
  findOneOrNone(
    query: ModelQuery<T>,
    errorArgs?: Partial<APIErrorConstructor>
  ): Promise<(Document & T) | null>;

  findExactlyOne(
    query: ModelQuery<T>,
    errorArgs?: Partial<APIErrorConstructor>
  ): Promise<Document & T>;
}

export interface DefaultPluginFields {
  created: Date;
  updated: Date;
  deleted: boolean;
}

export type DefaultModel<T> = Model<T & DefaultPluginFields> & DefaultStatics<T>;
export type DefaultDoc = mongoose.Document<mongoose.Types.ObjectId> & DefaultPluginFields;

export type UserMethods = {
  getDisplayName: (this: UserDocument) => string;
};

export type UserStatics = DefaultStatics<UserDocument> & {
  findByEmail: (this: UserModel, email: string) => Promise<UserDocument | null>;
};

export type UserModel = DefaultModel<UserDocument> &
  UserStatics &
  PassportLocalMongooseModel<UserDocument>;

export type UserSchema = mongoose.Schema<UserDocument, UserModel, UserMethods>;

export type UserDocument = DefaultDoc &
  UserMethods &
  PassportLocalMongooseDocument & {
    admin: boolean;
    betterAuthId?: string;
    email: string;
    name: string;
  };
`;
};

// Frontend file generators
const generateFrontendPackageJson = (args: BootstrapArgs): string => {
  const {appName} = args;
  return JSON.stringify(
    {
      dependencies: {
        "@expo/vector-icons": "^15.1.1",
        "@react-native-async-storage/async-storage": "2.2.0",
        "@reduxjs/toolkit": "^2.11.1",
        "@sentry/react": "^10.29.0",
        "@terreno/admin-frontend": TERRENO_DEP_VERSION,
        "@terreno/rtk": TERRENO_DEP_VERSION,
        "@terreno/syncdb": TERRENO_DEP_VERSION,
        "@terreno/ui": TERRENO_DEP_VERSION,
        expo: "~57.0.14",
        "expo-constants": "~57.0.12",
        "expo-router": "~57.0.14",
        "expo-sqlite": "~57.0.1",
        lodash: "^4.18.1",
        luxon: "^3.7.2",
        react: "19.2.3",
        "react-dom": "19.2.3",
        "react-native": "0.86.2",
        "react-native-reanimated": "4.5.1",
        "react-redux": "^9.2.0",
        "redux-persist": "^6.0.0",
      },
      devDependencies: {
        "@biomejs/biome": "^2.3.6",
        "@playwright/test": "^1.58.2",
        "@rtk-query/codegen-openapi": "^2.2.0",
        "@types/bun": "^1.4.0",
        "@types/lodash": "^4.17.17",
        "@types/luxon": "^3.7.1",
        "@types/react": "~19.2.14",
        "ts-node": "^10.9.2",
        tsx: "^4.23.12",
        typescript: "~6.0.3",
      },
      main: "expo-router/entry",
      name: `@${appName}/frontend`,
      private: true,
      scripts: {
        android: "EXPO_UNSTABLE_MCP_SERVER=1 bun expo start --android --port 8082",
        compile: "tsc",
        ios: "EXPO_UNSTABLE_MCP_SERVER=1 bun expo start --ios --port 8082",
        lint: "bun biome check .",
        "lint:fix": "bun biome check --write .",
        "lint:unsafefix": "biome check --write . --unsafe",
        sdk: "bun scripts/generate-sdk.ts && bun biome check --write scripts/generate-sdk.ts",
        start: "EXPO_UNSTABLE_MCP_SERVER=1 bun expo start --port 8082",
        test: "bun test",
        web: "EXPO_UNSTABLE_MCP_SERVER=1 bun expo start --web --port 8082",
      },
      version: "1.0.0",
    },
    null,
    2
  );
};

const generateFrontendAppJson = (args: BootstrapArgs): string => {
  const {appDisplayName, appName} = args;
  return JSON.stringify(
    {
      // No icon/splash/favicon keys: Expo falls back to its built-in defaults, so a freshly
      // generated app bundles without any binary assets. Add your own branding later and
      // point `icon`, `android.adaptiveIcon`, `splash`, and `web.favicon` at those files.
      expo: {
        experiments: {
          typedRoutes: true,
        },
        ios: {
          supportsTablet: true,
        },
        name: appDisplayName,
        orientation: "portrait",
        plugins: ["expo-router"],
        scheme: appName,
        slug: appName,
        userInterfaceStyle: "automatic",
        version: "1.0.0",
        web: {
          bundler: "metro",
          output: "static",
        },
      },
    },
    null,
    2
  );
};

const generateFrontendTsConfig = (): string => {
  // No `baseUrl`: it is deprecated as of TypeScript 6 and makes `tsc` abort with TS5101
  // before checking a single file. `paths` entries are relative to this tsconfig instead.
  // Module, target, JSX, and lib settings come from `expo/tsconfig.base`.
  return JSON.stringify(
    {
      compilerOptions: {
        paths: {
          "@/*": ["./*"],
          "@components/*": ["./components/*"],
          "@store": ["./store/index"],
          "@store/*": ["./store/*"],
          "@utils": ["./utils/index"],
          "@utils/*": ["./utils/*"],
        },
        strict: true,
        types: ["bun", "react-native", "@types/react"],
      },
      extends: "expo/tsconfig.base",
      include: ["**/*.ts", "**/*.tsx", ".expo/types/**/*.ts", "expo-env.d.ts"],
    },
    null,
    2
  );
};

const generateFrontendMetroConfig = (): string => {
  return `const {getDefaultConfig} = require("expo/metro-config");
const path = require("path");

const config = getDefaultConfig(__dirname);

const defaultResolveRequest = config.resolver.resolveRequest;

config.resolver.resolveRequest = (context, moduleName, platform) => {
  // @terreno/admin-frontend imports jspdf for its consent-PDF export. jspdf's CommonJS and
  // Node builds wrap an AMD-style \`require(["html2canvas"], cb)\` call that Metro's static
  // transform cannot parse, which fails the whole bundle — including Expo Router's static
  // web render, which resolves under a "node" condition and would otherwise pick
  // jspdf.node.min.js. Pin every jspdf request to the ESM browser build on web, and drop it
  // on native, where PDF export is unavailable and jspdf's browser/Node APIs are missing.
  if (moduleName === "jspdf" || moduleName.startsWith("jspdf/dist/jspdf.node")) {
    if (platform !== "web") {
      return {type: "empty"};
    }
    try {
      const jspdfDir = path.dirname(require.resolve("jspdf/package.json", {paths: [__dirname]}));
      return {
        filePath: path.join(jspdfDir, "dist", "jspdf.es.min.js"),
        type: "sourceFile",
      };
    } catch {
      // jspdf is not installed — let Metro report the failure itself.
    }
  }

  return defaultResolveRequest
    ? defaultResolveRequest(context, moduleName, platform)
    : context.resolveRequest(context, moduleName, platform);
};

module.exports = config;
`;
};

const generateFrontendTsConfigCodegen = (): string => {
  return JSON.stringify(
    {
      compilerOptions: {
        module: "commonjs",
        moduleResolution: "bundler",
        skipLibCheck: true,
        strict: true,
        target: "es2022",
      },
    },
    null,
    2
  );
};

const generateFrontendBiomeJsonc = (): string => {
  return `{
  "$schema": "./node_modules/@biomejs/biome/configuration_schema.json",
  "assist": {
    "actions": {
      "source": {
        "organizeImports": "on",
        "useSortedAttributes": "on",
        "useSortedKeys": "on"
      }
    },
    "enabled": true
  },
  "files": {
    "includes": [
      "package.json",
      "app/**/*.ts",
      "app/**/*.tsx",
      "components/**/*.ts",
      "components/**/*.tsx",
      "store/**/*.ts",
      "store/**/*.tsx",
      "utils/**/*.ts",
      "utils/**/*.tsx",
      "constants/**/*.ts",
      "scripts/**/*.ts",
      "!!**/node_modules",
      "!!**/dist",
      "!!**/build",
      "!!**/coverage",
      "!!**/.expo",
      "!!**/.next",
      "!!**/generated",
      "!!**/.git"
    ]
  },
  "formatter": {
    "enabled": true,
    "indentStyle": "space",
    "indentWidth": 2,
    "lineWidth": 100
  },
  "javascript": {
    "formatter": {
      "arrowParentheses": "always",
      "bracketSpacing": false,
      "jsxQuoteStyle": "double",
      "quoteStyle": "double",
      "semicolons": "always",
      "trailingCommas": "es5"
    },
    // TODO: Remove once we don't need to import React from 'react' in our JSX files.
    "jsxRuntime": "reactClassic"
  },
  "linter": {
    "enabled": true,
    "rules": {
      "nursery": {
        "noFloatingPromises": "error",
        "noMisusedPromises": "error",
        "useExhaustiveSwitchCases": "error"
      },
      "recommended": true,
      "suspicious": {
        "noConsole": {
          "level": "error",
          "options": {
            "allow": ["assert", "debug", "error", "info", "warn"]
          }
        },
        "noExplicitAny": "off",
        "noImplicitAnyLet": "off"
      }
    }
  },
  "vcs": {
    "clientKind": "git",
    "defaultBranch": "master",
    "enabled": true
  }
}
`;
};

const generateFrontendBetterAuthApi = (): string => {
  return `/**
 * RTK Query API base for Better Auth session cookies.
 *
 * Unlike \`@terreno/rtk\`'s JWT \`emptySplitApi\`, this base query reads the Better Auth
 * session token on every request and sends it as a Bearer header with credentials.
 */
import {createApi, fetchBaseQuery} from "@reduxjs/toolkit/query/react";
import {baseUrl, IsWeb, type VersionCheckResponse} from "@terreno/rtk";
import Constants from "expo-constants";
import {betterAuthClient} from "@/lib/betterAuth";

const readSessionToken = async (): Promise<string | null> => {
  try {
    const result = await betterAuthClient.getSession();
    const envelope = (result as {data?: {session?: {token?: string}}})?.data ?? result;
    const session = (envelope as {session?: {token?: string}})?.session;
    return session?.token ?? null;
  } catch {
    return null;
  }
};

const betterAuthBaseQuery = fetchBaseQuery({
  baseUrl,
  credentials: "include",
  prepareHeaders: async (headers) => {
    const token = await readSessionToken();
    if (token) {
      headers.set("authorization", \`Bearer \${token}\`);
    }
    const version = Constants.expoConfig?.version;
    if (version) {
      headers.set("App-Version", version);
    }
    headers.set("App-Platform", IsWeb ? "web" : "mobile");
    return headers;
  },
  responseHandler: async (response) => {
    if (response.status === 204) {
      return null;
    }
    const result = await response.json();
    if (result && typeof result === "object" && "more" in result) {
      return result;
    }
    if (result?.data) {
      return result.data;
    }
    return result;
  },
});

export const emptySplitApi = createApi({
  baseQuery: betterAuthBaseQuery,
  endpoints: (builder) => ({
    getVersionCheck: builder.query<VersionCheckResponse, {platform: string; version: number}>({
      query: ({platform, version}) => ({
        params: {platform, version},
        url: "/version-check",
      }),
    }),
  }),
  reducerPath: "terreno-rtk",
});

export const {useGetVersionCheckQuery, useLazyGetVersionCheckQuery} = emptySplitApi;
`;
};

const generateFrontendOpenApiConfig = (): string => {
  return `import type {ConfigFile} from "@rtk-query/codegen-openapi";

const config: ConfigFile = {
  apiFile: "./store/betterAuthApi.ts",
  apiImport: "emptySplitApi",
  argSuffix: "Args",
  exportName: "openapi",
  flattenArg: true,
  hooks: true,
  outputFile: "./store/openApiSdk.ts",
  responseSuffix: "Res",
  schemaFile: process.env.OPENAPI_URL ?? "http://localhost:4000/openapi.json",
  tag: true,
};

export default config;
`;
};

const generateFrontendGenerateSdk = (): string => {
  return `#!/usr/bin/env bun

import {execFile} from "node:child_process";
import {existsSync, readFileSync, realpathSync, writeFileSync} from "node:fs";
import {basename, dirname, extname, join, resolve, sep} from "node:path";

const cliPath = join(
  __dirname,
  "..",
  "node_modules",
  "@rtk-query",
  "codegen-openapi",
  "lib",
  "bin",
  "cli.mjs"
);
const configFile = process.argv[2] ?? "openapi-config.ts";
const sdkFile = process.argv[3] ?? "store/openApiSdk.ts";
const projectRoot = resolve(__dirname, "..");
const configPath = resolve(projectRoot, configFile);
const sdkPath = resolve(projectRoot, sdkFile);
const tsConfigPath = join(__dirname, "..", "tsconfig.codegen.json");
const canonicalProjectRoot = realpathSync(projectRoot);

const isProjectFile = (filePath: string): boolean => {
  if (!filePath.startsWith(\`\${projectRoot}\${sep}\`) || extname(filePath) !== ".ts") {
    return false;
  }
  try {
    const canonicalPath = existsSync(filePath)
      ? realpathSync(filePath)
      : resolve(realpathSync(dirname(filePath)), basename(filePath));
    return canonicalPath.startsWith(\`\${canonicalProjectRoot}\${sep}\`);
  } catch {
    return false;
  }
};

if (!isProjectFile(configPath) || !isProjectFile(sdkPath)) {
  console.error("SDK config and output must be TypeScript files inside frontend/");
  process.exit(1);
}

execFile(
  "tsx",
  [cliPath, configPath],
  {env: {...process.env, TS_NODE_PROJECT: tsConfigPath}},
  (error, _stdout, stderr) => {
    if (error) {
      console.error(\`Error: \${error.message}\`);
      process.exit(1);
    }
    if (stderr) {
      console.error(\`stderr: \${stderr}\`);
    }

    if (existsSync(sdkPath)) {
      let content = readFileSync(sdkPath, "utf8");
      content = content.replace(/^export const \\{\\} = injectedRtkApi;\\n?/m, "");
      if (!content.startsWith("// biome-ignore-all lint/suspicious/noExplicitAny")) {
        content =
          "// biome-ignore-all lint/suspicious/noExplicitAny: types are generated from backend OpenAPI schemas\\n" +
          content;
      }
      writeFileSync(sdkPath, content, "utf8");
    }

    execFile(
      "bunx",
      ["biome", "check", "--unsafe", "--write", sdkPath],
      {cwd: projectRoot},
      (formatError) => {
        if (formatError) {
          console.error(\`Formatting error: \${formatError.message}\`);
          process.exit(1);
        }
      }
    );
  }
);
`;
};

const generateFrontendRootLayout = (_args: BootstrapArgs): string => {
  return `import {DefaultTheme, ThemeProvider} from "expo-router/react-navigation";
import {Stack} from "expo-router";
import {useEffect} from "react";
import "react-native-reanimated";
import {baseUrl, selectBetterAuthIsLoading, selectBetterAuthUserId} from "@terreno/rtk";
import {SyncDbProvider} from "@terreno/syncdb/react";
import {Spinner, TerrenoProvider} from "@terreno/ui";
import {Provider, useSelector} from "react-redux";
import {PersistGate} from "redux-persist/integration/react";
import store, {persistor, syncBetterAuthSession} from "@/store/index";
import {setSyncDbReady, syncDb} from "@/store/syncdb";

export {ErrorBoundary} from "expo-router";

export const unstable_settings = {
  initialRouteName: "(tabs)",
};

// TerrenoProvider loads the Nunito/Titillium Web families @terreno/ui renders with, so this
// app ships no font assets of its own. Add \`useFonts\` here only for extra custom faces.
export default function RootLayout(): React.ReactElement | null {
  return (
    <Provider store={store}>
      <PersistGate loading={null} persistor={persistor}>
        <TerrenoProvider openAPISpecUrl={\`\${baseUrl}/openapi.json\`}>
          <RootLayoutNav />
        </TerrenoProvider>
      </PersistGate>
    </Provider>
  );
}

function RootLayoutNav(): React.ReactElement {
  const userId = useSelector(selectBetterAuthUserId) ?? undefined;
  const isAuthLoading = useSelector(selectBetterAuthIsLoading);

  // Hydrate Better Auth session into Redux on startup.
  useEffect(() => {
    void syncBetterAuthSession(store.dispatch);
  }, []);

  // Start syncdb after login; stop on logout.
  useEffect(() => {
    if (!userId) {
      setSyncDbReady(false);
      return;
    }
    let stopped = false;
    void syncDb
      .start()
      .then(() => {
        if (!stopped) {
          setSyncDbReady(true);
        }
      })
      .catch((startError: unknown) => {
        console.error("[syncdb] start failed", startError);
        setSyncDbReady(false);
      });
    return () => {
      stopped = true;
      setSyncDbReady(false);
      void syncDb.stop();
    };
  }, [userId]);

  if (isAuthLoading) {
    return <Spinner />;
  }

  return (
    <SyncDbProvider client={syncDb}>
      <ThemeProvider value={DefaultTheme}>
        {/* Stack.Protected is the supported way to gate routes on auth state. Rendering
            Stack.Screen children behind a raw conditional (or a fragment) crashes the
            navigator, because Stack reads its screen config off the child elements. */}
        <Stack>
          <Stack.Protected guard={!userId}>
            <Stack.Screen name="login" options={{headerShown: false}} />
            <Stack.Screen name="signup" options={{headerShown: false}} />
          </Stack.Protected>
          <Stack.Protected guard={Boolean(userId)}>
            <Stack.Screen name="(tabs)" options={{headerShown: false}} />
          </Stack.Protected>
        </Stack>
      </ThemeProvider>
    </SyncDbProvider>
  );
}
`;
};

const generateFrontendLogin = (): string => {
  return `import {baseUrl} from "@terreno/rtk";
import {LoginScreen} from "@terreno/ui";
import {useRouter} from "expo-router";
import type React from "react";
import {useCallback, useState} from "react";
import {betterAuthClient} from "@/lib/betterAuth";
import {syncBetterAuthSession, useAppDispatch} from "@/store/index";

const Login: React.FC = () => {
  const router = useRouter();
  const dispatch = useAppDispatch();
  const [errorMessage, setErrorMessage] = useState<string | undefined>(undefined);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const handleSubmit = useCallback(
    async (values: Record<string, string>): Promise<void> => {
      const {email, password} = values;
      setErrorMessage(undefined);
      setIsSubmitting(true);
      try {
        const result = await betterAuthClient.signIn.email({email, password});
        if (result.error) {
          setErrorMessage(result.error.message ?? "Sign in failed.");
          return;
        }
        await syncBetterAuthSession(dispatch);
        router.replace("/(tabs)");
      } catch (error: unknown) {
        console.error("[login] Sign in threw", {baseUrl, error});
        setErrorMessage("Sign in failed. Please try again.");
      } finally {
        setIsSubmitting(false);
      }
    },
    [dispatch, router]
  );

  return (
    <LoginScreen
      error={errorMessage}
      fields={[
        {autoComplete: "off", label: "Email", name: "email", required: true, type: "email"},
        {label: "Password", name: "password", required: true, type: "password"},
      ]}
      loading={isSubmitting}
      onSignUpPress={() => router.push("/signup")}
      onSubmit={handleSubmit}
      title="Welcome"
    />
  );
};

export default Login;
`;
};

const generateFrontendSignup = (): string => {
  return `import {SignUpScreen, simplePasswordRequirements} from "@terreno/ui";
import {useRouter} from "expo-router";
import type React from "react";
import {useCallback, useState} from "react";
import {betterAuthClient} from "@/lib/betterAuth";
import {syncBetterAuthSession, useAppDispatch} from "@/store/index";

const SignUp: React.FC = () => {
  const router = useRouter();
  const dispatch = useAppDispatch();
  const [errorMessage, setErrorMessage] = useState<string | undefined>(undefined);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const handleSubmit = useCallback(
    async (values: Record<string, string>): Promise<void> => {
      const {email, password, name} = values;
      setErrorMessage(undefined);
      setIsSubmitting(true);
      try {
        const result = await betterAuthClient.signUp.email({email, name, password});
        if (result.error) {
          setErrorMessage(result.error.message ?? "Sign up failed.");
          return;
        }
        await syncBetterAuthSession(dispatch);
        router.replace("/(tabs)");
      } catch {
        setErrorMessage("Sign up failed. Please try again.");
      } finally {
        setIsSubmitting(false);
      }
    },
    [dispatch, router]
  );

  return (
    <SignUpScreen
      error={errorMessage}
      fields={[
        {label: "Name", name: "name", required: true, type: "text"},
        {autoComplete: "off", label: "Email", name: "email", required: true, type: "email"},
        {label: "Password", name: "password", required: true, type: "password"},
      ]}
      loading={isSubmitting}
      onLoginPress={() => router.back()}
      onSubmit={handleSubmit}
      passwordRequirements={simplePasswordRequirements}
    />
  );
};

export default SignUp;
`;
};

const generateFrontendTabsLayout = (): string => {
  return `import FontAwesome from "@expo/vector-icons/FontAwesome";
import {useTheme} from "@terreno/ui";
import {Tabs} from "expo-router";
import type React from "react";
import type {ColorValue} from "react-native";

const TabBarIcon: React.FC<{
  name: React.ComponentProps<typeof FontAwesome>["name"];
  color: ColorValue;
}> = ({name, color}) => {
  return <FontAwesome color={color} name={name} size={24} style={{marginBottom: -3}} />;
};

const TabLayout: React.FC = () => {
  const {theme} = useTheme();

  return (
    <Tabs
      screenOptions={{
        headerShown: false,
        tabBarActiveTintColor: theme.surface.primary,
      }}
    >
      <Tabs.Screen
        name="index"
        options={{
          tabBarIcon: ({color}) => <TabBarIcon color={color} name="home" />,
          title: "Home",
        }}
      />
      <Tabs.Screen
        name="profile"
        options={{
          headerShown: false,
          tabBarIcon: ({color}) => <TabBarIcon color={color} name="user" />,
          title: "Profile",
        }}
      />
      <Tabs.Screen
        name="admin"
        options={{
          headerShown: false,
          tabBarIcon: ({color}) => <TabBarIcon color={color} name="cog" />,
          title: "Admin",
        }}
      />
    </Tabs>
  );
};

export default TabLayout;
`;
};

const generateFrontendTabsIndex = (args: BootstrapArgs): string => {
  const {appDisplayName} = args;
  return `import {Box, Heading, Page, Text} from "@terreno/ui";
import type React from "react";

const HomeScreen: React.FC = () => {
  return (
    <Page navigation={undefined} title="Home">
      <Box padding={4} gap={4}>
        <Heading>Welcome to ${appDisplayName}</Heading>
        <Text>Your app is ready for development!</Text>
        <Text color="secondaryDark">
          Start by adding models to the backend and screens to the frontend.
        </Text>
      </Box>
    </Page>
  );
};

export default HomeScreen;
`;
};

const generateFrontendTabsProfile = (): string => {
  return `import {Box, Button, Card, Heading, Page, Spinner, TapToEdit, Text} from "@terreno/ui";
import type React from "react";
import {useCallback, useEffect, useState} from "react";
import {signOut} from "@/lib/betterAuth";
import {logout, syncBetterAuthSession, useAppDispatch} from "@/store/index";
import {useGetMeQuery, usePatchMeMutation} from "@/store/sdk";

const ProfileScreen: React.FC = () => {
  const dispatch = useAppDispatch();
  const {data: profile, isLoading} = useGetMeQuery();
  const [updateProfile] = usePatchMeMutation();
  const [name, setName] = useState<string>("");
  const [email, setEmail] = useState<string>("");
  const [password, setPassword] = useState<string>("");
  const [saveError, setSaveError] = useState<string | null>(null);

  const user = profile;

  // Copy the server name into local state without resetting an in-progress email edit.
  useEffect(() => {
    if (!user) {
      return;
    }
    setName(user.name || "");
  }, [user?.name]);

  // Copy the server email into local state without resetting an in-progress name edit.
  useEffect(() => {
    if (!user) {
      return;
    }
    setEmail(user.email || "");
  }, [user?.email]);

  const handleLogout = useCallback(async (): Promise<void> => {
    await signOut();
    dispatch(logout());
    await syncBetterAuthSession(dispatch);
  }, [dispatch]);

  const handleSaveName = useCallback(
    async (value: string): Promise<void> => {
      setSaveError(null);
      try {
        await updateProfile({name: value}).unwrap();
      } catch (err) {
        console.error("Error updating name:", err);
        setSaveError("Failed to update name");
      }
    },
    [updateProfile]
  );

  const handleSaveEmail = useCallback(
    async (value: string): Promise<void> => {
      setSaveError(null);
      try {
        await updateProfile({email: value}).unwrap();
      } catch (err) {
        console.error("Error updating email:", err);
        setSaveError("Failed to update email");
      }
    },
    [updateProfile]
  );

  const handleSavePassword = useCallback(
    async (value: string): Promise<void> => {
      if (!value) {
        return;
      }
      setSaveError(null);
      try {
        await updateProfile({password: value}).unwrap();
        setPassword("");
      } catch (err) {
        console.error("Error updating password:", err);
        setSaveError("Failed to update password");
      }
    },
    [updateProfile]
  );

  if (isLoading) {
    return (
      <Page navigation={undefined} title="Profile">
        <Box alignItems="center" flex="grow" justifyContent="center" padding={4}>
          <Spinner />
        </Box>
      </Page>
    );
  }

  return (
    <Page navigation={undefined} scroll title="Profile">
      <Box gap={4} padding={4}>
        <Heading>Profile</Heading>
        <Card>
          <Box gap={4}>
            <TapToEdit
              onSave={handleSaveName}
              setValue={setName}
              title="Name"
              type="text"
              value={name}
            />
            <TapToEdit
              onSave={handleSaveEmail}
              setValue={setEmail}
              title="Email"
              type="email"
              value={email}
            />
            <TapToEdit
              helperText="Leave blank to keep your current password"
              onSave={handleSavePassword}
              setValue={setPassword}
              title="New Password"
              type="password"
              value={password}
            />
            {saveError && <Text color="error">{saveError}</Text>}
          </Box>
        </Card>
        <Box marginTop={4}>
          <Button fullWidth onClick={handleLogout} text="Logout" variant="outline" />
        </Box>
      </Box>
    </Page>
  );
};

export default ProfileScreen;
`;
};

const generateFrontendAdminLayout = (): string => {
  return `import {Stack} from "expo-router";
import type React from "react";

const AdminLayout: React.FC = () => {
  return <Stack screenOptions={{headerShown: false}} />;
};

export default AdminLayout;
`;
};

const generateFrontendAdminIndex = (): string => {
  return `import {AdminModelList} from "@terreno/admin-frontend";
import type React from "react";
import {adminTerrenoApi} from "@/store/sdk";

const AdminListScreen: React.FC = () => {
  return (
    <AdminModelList
      api={adminTerrenoApi}
      baseUrl="/admin"
      configurationPath="/admin/configuration"
    />
  );
};

export default AdminListScreen;
`;
};

const generateFrontendAdminConfiguration = (): string => {
  return `import {ConfigurationScreen} from "@terreno/admin-frontend";
import type React from "react";
import {adminTerrenoApi} from "@/store/sdk";

const ConfigurationPage: React.FC = () => {
  return <ConfigurationScreen api={adminTerrenoApi} />;
};

export default ConfigurationPage;
`;
};

const generateFrontendNotFound = (): string => {
  return `import {Box, Heading, Text} from "@terreno/ui";
import {Link, Stack} from "expo-router";
import type React from "react";

const NotFoundScreen: React.FC = () => {
  return (
    <>
      <Stack.Screen options={{title: "Oops!"}} />
      <Box alignItems="center" flex="grow" justifyContent="center" padding={4}>
        <Heading size="xl">This screen doesn't exist.</Heading>
        <Link href="/" style={{marginTop: 15, paddingVertical: 15}}>
          <Text color="link" size="md">
            Go to home screen!
          </Text>
        </Link>
      </Box>
    </>
  );
};

export default NotFoundScreen;
`;
};

const generateFrontendStoreIndex = (): string => {
  return `import AsyncStorage from "@react-native-async-storage/async-storage";
import {combineReducers, configureStore, type Store} from "@reduxjs/toolkit";
import {
  type BetterAuthClientInterface,
  generateBetterAuthSlice,
  registerTerrenoDevStore,
} from "@terreno/rtk";
import {DateTime} from "luxon";
import {useDispatch} from "react-redux";
import type {Storage} from "redux-persist";
import {persistReducer, persistStore} from "redux-persist";
import {betterAuthClient} from "@/lib/betterAuth";

import appState from "./appState";
import {rtkQueryErrorMiddleware} from "./errors";
import {terrenoApi} from "./sdk";

const betterAuth = generateBetterAuthSlice({
  authClient: betterAuthClient as unknown as BetterAuthClientInterface,
});

export const logout = betterAuth.actions.logout;
export const syncBetterAuthSession = betterAuth.syncSession;

const createSafeStorage = (): Storage => {
  return {
    getItem: async (key: string): Promise<string | null> => {
      if (typeof window !== "undefined") {
        return AsyncStorage.getItem(key);
      }
      return null;
    },
    removeItem: async (key: string): Promise<void> => {
      if (typeof window !== "undefined") {
        return AsyncStorage.removeItem(key);
      }
    },
    setItem: async (key: string, value: string): Promise<void> => {
      if (typeof window !== "undefined") {
        return AsyncStorage.setItem(key, value);
      }
    },
  };
};

const persistConfig = {
  blacklist: ["terreno-rtk", "betterAuth"],
  key: "root",
  storage: createSafeStorage(),
  timeout: 0,
  version: 1,
};

const rootReducer = combineReducers({
  appState,
  betterAuth: betterAuth.reducer,
  "terreno-rtk": terrenoApi.reducer,
});

const persistedReducer = persistReducer(persistConfig, rootReducer);

const store = configureStore({
  devTools: process.env.NODE_ENV !== "production" && {
    name: \`App-\${
      typeof window !== "undefined"
        // biome-ignore lint/suspicious/noAssignInExpressions: Window name assignment
        ? window.name || ((window.name = \`Window-\${DateTime.now().toFormat("HH:mm:ss")}\`))
        : "Unknown"
    }\`,
  },
  middleware: (getDefaultMiddleware) => {
    return getDefaultMiddleware({
      immutableCheck: false,
      serializableCheck: false,
      thunk: true,
    }).concat([
      ...betterAuth.middleware,
// noExplicitAny: RTK Query middleware typing
      // biome-ignore lint/suspicious/noExplicitAny: RTK Query middleware typing
      terrenoApi.middleware as any,
      rtkQueryErrorMiddleware,
// noExplicitAny: Middleware array typing
      // biome-ignore lint/suspicious/noExplicitAny: Middleware array typing
    ]) as any;
  },
  reducer: persistedReducer,
});

registerTerrenoDevStore(store as unknown as Store<Record<string, unknown>>);

export const persistor = persistStore(store);

export type RootState = ReturnType<typeof store.getState>;
export type AppDispatch = typeof store.dispatch;

export const useAppDispatch: () => AppDispatch = useDispatch;

export default store;
`;
};

const generateFrontendStoreAppState = (): string => {
  return `import {createSlice, type PayloadAction} from "@reduxjs/toolkit";
import {type TypedUseSelectorHook, useSelector} from "react-redux";
import type {RootState} from "./index";

export const useAppSelector: TypedUseSelectorHook<RootState> = useSelector;

export type AppState = {
  darkMode: boolean;
  language: string;
};

const initialState: AppState = {
  darkMode: false,
  language: "en",
};

export const appStateSlice = createSlice({
  initialState,
  name: "appState",
  reducers: {
    resetAppState: () => initialState,
    setDarkMode: (state, action: PayloadAction<boolean>) => {
      state.darkMode = action.payload;
    },
    setLanguage: (state, action: PayloadAction<string>) => {
      state.language = action.payload;
    },
  },
});

export const {setDarkMode, setLanguage, resetAppState} = appStateSlice.actions;

export const useSelectDarkMode = (): boolean => {
  return useAppSelector((state) => state.appState.darkMode);
};

export const useSelectLanguage = (): string => {
  return useAppSelector((state) => state.appState.language);
};

export default appStateSlice.reducer;
`;
};

const generateFrontendStoreErrors = (): string => {
  return `import type {Middleware} from "@reduxjs/toolkit";
import {useToast} from "@terreno/ui";

const ignoredErrors = [
  "Password or username is incorrect",
  "Token refresh failed with 401",
  "Failed to refresh token",
];

// noExplicitAny: Generic middleware
// biome-ignore lint/suspicious/noExplicitAny: Generic middleware
export const rtkQueryErrorMiddleware: Middleware = () => (next) => (action: any) => {
  if (action?.error && action?.payload) {
    const errorMessage =
      action.payload?.data?.title ??
      action.payload?.data?.message ??
      action.payload?.error ??
      JSON.stringify(action.payload);

    let endpointInfo = "unknown endpoint";
    if (action.meta?.baseQueryMeta?.request?.method && action.meta?.baseQueryMeta?.request?.url) {
      endpointInfo = \`\${action.meta.baseQueryMeta.request.url} \${action.meta.baseQueryMeta.request.method}\`;
    } else if (action.meta?.arg?.endpointName) {
      endpointInfo = \`\${action.meta.arg.endpointName} rejected \${action.meta.arg.type || ""}\`;
    }

    const message = \`\${endpointInfo.trim()}: \${errorMessage}\`;
    console.debug(message);

    if (action.payload.status === 404 || action.payload.status === 401) {
      return next(action);
    }

    const shouldIgnore = ignoredErrors.some((err) => errorMessage.includes(err));
    if (!shouldIgnore) {
      console.warn(message);
    }
  }

  return next(action);
};

export const useSentryAndToast = (): ((errorMessage: string) => void) => {
  const toast = useToast();
  return (error: string): void => {
    if (!error) {
      return;
    }
    toast.error(error);
    console.warn(\`Error: \${error}\`);
  };
};
`;
};

const generateFrontendStoreSdk = (): string => {
  return `import type {AdminScreenProps} from "@terreno/admin-frontend";
import {generateTags} from "@terreno/rtk";
import startCase from "lodash/startCase";

import {addTagTypes, openapi} from "./openApiSdk";

/** emptyApi unwraps the \`data\` envelope — profile fields are top-level on the response. */
export interface ProfileResponse {
  _id: string;
  id: string;
  email: string;
  name: string;
}

export interface UpdateProfileRequest {
  name?: string;
  email?: string;
  password?: string;
}

export const terrenoApi = openapi
  .enhanceEndpoints({
    addTagTypes: ["profile"],
  })
  .injectEndpoints({
    endpoints: (builder) => ({
      getMe: builder.query<ProfileResponse, void>({
        providesTags: ["profile"],
        query: () => ({
          method: "GET",
          url: "/auth/me",
        }),
      }),
      patchMe: builder.mutation<ProfileResponse, UpdateProfileRequest>({
        invalidatesTags: ["profile"],
        query: (body) => ({
          body,
          method: "PATCH",
          url: "/auth/me",
        }),
      }),
    }),
  })
  .enhanceEndpoints({
    endpoints: {
      ...generateTags(openapi, [...addTagTypes]),
    },
  });

/** Type-erased API instance for @terreno/admin-frontend screens. */
export const adminTerrenoApi = terrenoApi as unknown as AdminScreenProps["api"];

export const {
  useGetMeQuery,
  usePatchMeMutation,
} = terrenoApi;
export * from "./openApiSdk";

type OpenApiEndpoints = Record<string, unknown>;

export const getSdkHook = (
  modelName: string,
  type: "list" | "read" | "create" | "update" | "remove"
): Record<string, unknown> => {
  const modelPath = startCase(modelName).replace(/\\s/g, "");
  const endpoints = openapi.endpoints as OpenApiEndpoints;
  switch (type) {
    case "list":
      return endpoints[\`get\${modelPath}\`] as Record<string, unknown>;
    case "read":
      return endpoints[\`get\${modelPath}ById\`] as Record<string, unknown>;
    case "create":
      return endpoints[\`post\${modelPath}\`] as Record<string, unknown>;
    case "update":
      return endpoints[\`patch\${modelPath}ById\`] as Record<string, unknown>;
    case "remove":
      return endpoints[\`delete\${modelPath}ById\`] as Record<string, unknown>;
    default:
      throw new Error(\`Invalid SDK hook: \${modelName}/\${type}\`);
  }
};
`;
};

const generateFrontendStoreOpenApiSdk = (): string => {
  return `// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Run "bun run sdk" to regenerate this file from the backend OpenAPI spec.

import {emptySplitApi as api} from "./betterAuthApi";
export const addTagTypes = ["Users", "Auth", "profile"] as const;
const injectedRtkApi = api
  .enhanceEndpoints({
    addTagTypes,
  })
  .injectEndpoints({
    endpoints: () => ({}),
    overrideExisting: false,
  });
export {injectedRtkApi as openapi};
`;
};

const generateFrontendTheme = (): string => {
  return `// Theme configuration for the app
// Override these values to customize the app's appearance
// Colors are based on @terreno/ui's default theme primitives

export const primitives = {
  // Primary colors (teal/cyan)
  primary000: "#EBFAFF",
  primary050: "#BCE9F7",
  primary100: "#90D8F0",
  primary200: "#73CAE8",
  primary300: "#40B8E0",
  primary400: "#0E9DCD",
  primary500: "#0086B3",
  primary600: "#0A7092",
  primary700: "#035D7E",
  primary800: "#004B64",
  primary900: "#013749",

  // Secondary colors (dark teal)
  secondary000: "#F2F9FA",
  secondary050: "#D7E5EA",
  secondary100: "#B6CDD5",
  secondary200: "#9EB7BF",
  secondary300: "#87A1AA",
  secondary400: "#608997",
  secondary500: "#2B6072",
  secondary600: "#1C4E5F",
  secondary700: "#0F3D4D",
  secondary800: "#092E3A",
  secondary900: "#041E27",

  // Accent colors (gold/yellow)
  accent000: "#FFFDF7",
  accent050: "#FCECC2",
  accent100: "#F9E0A1",
  accent200: "#F7D582",
  accent300: "#F2CB62",
  accent400: "#E5B132",
  accent500: "#D69C0E",
  accent600: "#B58201",
  accent700: "#956A00",
  accent800: "#543C00",
  accent900: "#332400",

  // Neutral colors (grays)
  neutral000: "#FFFFFF",
  neutral050: "#F2F2F2",
  neutral100: "#E6E6E6",
  neutral200: "#D9D9D9",
  neutral300: "#CDCDCD",
  neutral400: "#B3B3B3",
  neutral500: "#949494",
  neutral600: "#686868",
  neutral700: "#4E4E4E",
  neutral800: "#353535",
  neutral900: "#1C1C1C",

  // Status colors
  error000: "#FDD7D7",
  error100: "#D33232",
  error200: "#BD1111",
  success000: "#DCF2E2",
  success100: "#3EA45C",
  success200: "#1A7F36",
  warning000: "#FFE3C6",
  warning100: "#F36719",
  warning200: "#B14202",
};

// Semantic color mappings - override these to change app appearance
export const colors = {
  // Backgrounds
  background: primitives.neutral000,
  backgroundSecondary: primitives.neutral050,

  // Text
  text: primitives.neutral900,
  textSecondary: primitives.neutral600,
  textInverted: primitives.neutral000,

  // Primary action colors
  primary: primitives.primary400,
  primaryDark: primitives.primary600,
  primaryLight: primitives.primary100,

  // Secondary colors
  secondary: primitives.secondary500,
  secondaryDark: primitives.secondary700,
  secondaryLight: primitives.secondary100,

  // Accent colors
  accent: primitives.accent500,
  accentDark: primitives.accent700,
  accentLight: primitives.accent100,

  // Status colors
  error: primitives.error100,
  errorLight: primitives.error000,
  success: primitives.success100,
  successLight: primitives.success000,
  warning: primitives.warning100,
  warningLight: primitives.warning000,

  // UI elements
  border: primitives.neutral300,
  borderFocus: primitives.primary200,
  icon: primitives.neutral600,
  tint: primitives.primary400,

  // Tab bar
  tabIconDefault: primitives.neutral600,
  tabIconSelected: primitives.primary400,
};

export default colors;
`;
};

const generateFrontendEnv = (): string => {
  return `EXPO_PUBLIC_API_URL=http://localhost:4000
`;
};

const generateBackendEnvExample = (args: BootstrapArgs): string => {
  const {appName} = args;
  const dbName = appName.replace(/-/g, "_");
  return `# Copy to backend/.env and fill in production values (Secret Manager / platform secrets).
# MongoDB must be a replica set for sync and realtime — see deployment baseline docs.

MONGO_URI=mongodb://127.0.0.1:27017/${dbName}?replicaSet=rs0
AUTH_PROVIDER=better-auth
BETTER_AUTH_SECRET=
BETTER_AUTH_URL=https://api.example.com
CORS_ORIGINS=https://app.example.com
TOKEN_SECRET=
TOKEN_ISSUER=
REFRESH_TOKEN_SECRET=
SESSION_SECRET=
PORT=8080
NODE_ENV=production
`;
};

const generateFrontendEnvExample = (): string => {
  return `# Copy to frontend/.env for local dev, or export before web build.
# EXPO_PUBLIC_* is inlined at export time — set before \`bun expo export --platform web\`.

EXPO_PUBLIC_API_URL=https://api.example.com
`;
};

const generateBackendEnv = (args: BootstrapArgs): string => {
  const {appName} = args;
  const dbName = appName.replace(/-/g, "_");
  return `MONGO_URI=mongodb://127.0.0.1:27017/${dbName}?replicaSet=rs0
AUTH_PROVIDER=better-auth
BETTER_AUTH_SECRET=${appName}-better-auth-secret-dev-only-32chars
BETTER_AUTH_URL=http://localhost:4000
TOKEN_SECRET=dev-token-secret
TOKEN_ISSUER=${appName}-dev
REFRESH_TOKEN_SECRET=dev-refresh-secret
SESSION_SECRET=dev-session-secret
PORT=4000
`;
};

const generateFrontendBetterAuthLib = (args: BootstrapArgs): string => {
  const {appName} = args;
  return `import {baseUrl, createBetterAuthClient} from "@terreno/rtk";
import Constants from "expo-constants";

const getAppScheme = (): string => {
  const expoExtra = Constants.expoConfig?.extra;
  return expoExtra?.scheme ?? "${appName}";
};

export const betterAuthClient = createBetterAuthClient({
  baseURL: baseUrl,
  scheme: getAppScheme(),
  storagePrefix: "${appName}",
});

export const signOut = async (): Promise<void> => {
  await betterAuthClient.signOut();
};
`;
};

const generateFrontendSyncDb = (args: BootstrapArgs): string => {
  const {appName} = args;
  const dbName = appName.replace(/-/g, "-");
  return `import {baseUrl} from "@terreno/rtk";
import {
  type BetterAuthClientLike,
  betterAuthAdapter,
  createSyncDb,
  type SyncDb,
} from "@terreno/syncdb";
import {betterAuthClient} from "@/lib/betterAuth";

export const SYNC_DB_NAME = "${dbName}";

/** Add synced collection names here as you register modelRouter sync scopes on the backend. */
export const SYNC_COLLECTIONS: string[] = [];

/**
 * The Better Auth *react* client delivers session changes through a nanostore atom
 * (\`$store.atoms.session\`), but its \`useSession\` is a React hook without \`.subscribe\`.
 * betterAuthAdapter looks for \`useSession.subscribe\`; without it, it falls back to
 * polling \`getSession()\` every 5s (constant /api/auth/get-session traffic). Bridge the
 * atom to the shape the adapter expects so auth changes are event-driven instead.
 */
type SessionAtomLike = {subscribe: (listener: (value: unknown) => void) => () => void};
const sessionAtom = (
  betterAuthClient as unknown as {$store?: {atoms?: {session?: SessionAtomLike}}}
).$store?.atoms?.session;

const syncAuthClient: BetterAuthClientLike = {
  getSession: () => betterAuthClient.getSession(),
  ...(sessionAtom
    ? {useSession: {subscribe: (listener): (() => void) => sessionAtom.subscribe(listener)}}
    : {}),
};

// pollIntervalMs is only used as a fallback if the session atom bridge above is
// unavailable (e.g. a future Better Auth client shape change); keep it slow.
const authProvider = betterAuthAdapter(syncAuthClient, {pollIntervalMs: 60_000});

export const syncDb: SyncDb = createSyncDb({
  authProvider,
  baseUrl,
  collections: SYNC_COLLECTIONS,
  name: SYNC_DB_NAME,
});

let syncDbReady = false;
const syncDbReadyListeners = new Set<() => void>();

export const setSyncDbReady = (ready: boolean): void => {
  if (syncDbReady === ready) {
    return;
  }
  syncDbReady = ready;
  for (const listener of syncDbReadyListeners) {
    listener();
  }
};

export const subscribeSyncDbReady = (listener: () => void): (() => void) => {
  syncDbReadyListeners.add(listener);
  return () => {
    syncDbReadyListeners.delete(listener);
  };
};

export const getSyncDbReadySnapshot = (): boolean => syncDbReady;
`;
};

const generateFrontendUtilsIndex = (): string => {
  return `export const captureException = (error: unknown): void => {
  console.error("Captured exception:", error);
};

export const captureMessage = (message: string): void => {
  console.warn("Captured message:", message);
};

export const createSentryReduxEnhancer = (): unknown => {
  return undefined;
};
`;
};

const generateBackendCiWorkflow = (_args: BootstrapArgs): string => {
  return `name: Backend CI

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"

jobs:
  lint-and-test:
    name: Backend Lint, Build, and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ["6.0"]
    steps:
      - uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Cache Bun dependencies
        id: cache
        uses: actions/cache@v5
        with:
          path: |
            ~/.bun/install/cache
            node_modules
          key: bun-\${{ runner.os }}-\${{ github.ref }}-\${{ hashFiles('bun.lock', 'package.json') }}
          restore-keys: |
            bun-\${{ runner.os }}-\${{ github.ref }}-
            bun-\${{ runner.os }}-

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.1
        with:
          mongodb-version: \${{ matrix.mongodb-version }}

      - name: Install dependencies
        run: bun install
        working-directory: backend

      - name: Lint
        run: bun run lint
        working-directory: backend

      - name: Build
        run: bun run compile
        working-directory: backend

      - name: Test
        run: bun run test
        working-directory: backend
        env:
          CI: true
`;
};

const generateFrontendCiWorkflow = (_args: BootstrapArgs): string => {
  return `name: Frontend CI

on:
  push:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-ci.yml"

jobs:
  lint-and-test:
    name: Frontend Lint, Build, and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Cache Bun dependencies
        id: cache
        uses: actions/cache@v5
        with:
          path: |
            ~/.bun/install/cache
            node_modules
          key: bun-\${{ runner.os }}-\${{ github.ref }}-\${{ hashFiles('bun.lock', 'package.json') }}
          restore-keys: |
            bun-\${{ runner.os }}-\${{ github.ref }}-
            bun-\${{ runner.os }}-

      - name: Install dependencies
        run: bun install
        working-directory: frontend

      - name: Lint
        run: bun run lint
        working-directory: frontend

      - name: TypeScript compile
        run: bun run compile
        working-directory: frontend

      - name: Test
        run: bun run test
        working-directory: frontend
        env:
          CI: true
`;
};

export const getFenceLanguage = (filePath: string): string => {
  if (filePath.endsWith(".json") || filePath.endsWith(".jsonc")) {
    return "json";
  }
  if (filePath.endsWith(".js")) {
    return "javascript";
  }
  if (filePath.endsWith(".yml") || filePath.endsWith(".yaml")) {
    return "yaml";
  }
  if (filePath.endsWith(".md")) {
    return "markdown";
  }
  return "typescript";
};

export const generateAllFiles = (args: BootstrapArgs): GeneratedFile[] => {
  const frontendDir = `frontend`;
  const backendDir = `backend`;

  return [
    // Root files
    {content: generateRootGitignore(), path: ".gitignore"},
    {content: generateRootReadme(args), path: "README.md"},
    {content: generateRootDockerignore(), path: ".dockerignore"},
    {content: generateRootDockerfile(), path: "Dockerfile"},
    {content: generateCursorRules(args), path: ".cursorrules"},
    {content: generateMcpSettings(args), path: ".cursor/mcp.json"},
    {content: generateClaudeMd(args), path: "CLAUDE.md"},

    // Backend files
    {content: generateBackendPackageJson(args), path: `${backendDir}/package.json`},
    {content: generateBackendTsConfig(), path: `${backendDir}/tsconfig.json`},
    {content: generateBackendBiomeJsonc(), path: `${backendDir}/biome.jsonc`},
    {content: generateBackendIndex(), path: `${backendDir}/src/index.ts`},
    {content: generateBackendAccess(), path: `${backendDir}/src/access.ts`},
    {content: generateBackendServer(args), path: `${backendDir}/src/server.ts`},
    {content: generateBackendDatabase(args), path: `${backendDir}/src/utils/database.ts`},
    {content: generateBackendSeed(args), path: `${backendDir}/src/scripts/seed.ts`},
    {
      content: generateBackendBetterAuthConfig(args),
      path: `${backendDir}/src/utils/betterAuthConfig.ts`,
    },
    {content: generateBackendEnv(args), path: `${backendDir}/.env`},
    {content: generateBackendEnvExample(args), path: `${backendDir}/.env.example`},
    {content: generateBackendModelPlugins(), path: `${backendDir}/src/models/modelPlugins.ts`},
    {content: generateBackendUserModel(), path: `${backendDir}/src/models/user.ts`},
    {
      content: generateBackendOrganizationSettings(),
      path: `${backendDir}/src/models/organizationSettings.ts`,
    },
    {
      content: generateBackendAppConfiguration(args),
      path: `${backendDir}/src/models/appConfiguration.ts`,
    },
    {content: generateBackendModelsIndex(), path: `${backendDir}/src/models/index.ts`},
    {content: generateBackendUserRoutes(), path: `${backendDir}/src/api/users.ts`},
    {content: generateBackendTypes(), path: `${backendDir}/src/types/index.ts`},
    {content: generateBackendTypesModels(), path: `${backendDir}/src/types/models/index.ts`},
    {content: generateBackendUserTypes(), path: `${backendDir}/src/types/models/userTypes.ts`},
    {
      content: generateBackendOrganizationSettingsTypes(),
      path: `${backendDir}/src/types/models/organizationSettingsTypes.ts`,
    },

    // Frontend files
    {content: generateFrontendPackageJson(args), path: `${frontendDir}/package.json`},
    {content: generateFrontendAppJson(args), path: `${frontendDir}/app.json`},
    {content: generateFrontendTsConfig(), path: `${frontendDir}/tsconfig.json`},
    {content: generateFrontendTsConfigCodegen(), path: `${frontendDir}/tsconfig.codegen.json`},
    {content: generateFrontendMetroConfig(), path: `${frontendDir}/metro.config.js`},
    {content: generateFrontendBiomeJsonc(), path: `${frontendDir}/biome.jsonc`},
    {content: generateFrontendOpenApiConfig(), path: `${frontendDir}/openapi-config.ts`},
    {content: generateFrontendGenerateSdk(), path: `${frontendDir}/scripts/generate-sdk.ts`},
    {content: generateFrontendRootLayout(args), path: `${frontendDir}/app/_layout.tsx`},
    {content: generateFrontendLogin(), path: `${frontendDir}/app/login.tsx`},
    {content: generateFrontendSignup(), path: `${frontendDir}/app/signup.tsx`},
    {content: generateFrontendNotFound(), path: `${frontendDir}/app/+not-found.tsx`},
    {content: generateFrontendTabsLayout(), path: `${frontendDir}/app/(tabs)/_layout.tsx`},
    {content: generateFrontendTabsIndex(args), path: `${frontendDir}/app/(tabs)/index.tsx`},
    {content: generateFrontendTabsProfile(), path: `${frontendDir}/app/(tabs)/profile.tsx`},
    {content: generateFrontendAdminLayout(), path: `${frontendDir}/app/(tabs)/admin/_layout.tsx`},
    {content: generateFrontendAdminIndex(), path: `${frontendDir}/app/(tabs)/admin/index.tsx`},
    {
      content: generateFrontendAdminConfiguration(),
      path: `${frontendDir}/app/(tabs)/admin/configuration.tsx`,
    },
    {content: generateFrontendStoreIndex(), path: `${frontendDir}/store/index.ts`},
    {content: generateFrontendStoreAppState(), path: `${frontendDir}/store/appState.ts`},
    {content: generateFrontendStoreErrors(), path: `${frontendDir}/store/errors.ts`},
    {content: generateFrontendStoreSdk(), path: `${frontendDir}/store/sdk.ts`},
    {content: generateFrontendBetterAuthApi(), path: `${frontendDir}/store/betterAuthApi.ts`},
    {content: generateFrontendStoreOpenApiSdk(), path: `${frontendDir}/store/openApiSdk.ts`},
    {content: generateFrontendBetterAuthLib(args), path: `${frontendDir}/lib/betterAuth.ts`},
    {content: generateFrontendSyncDb(args), path: `${frontendDir}/store/syncdb.ts`},
    {content: generateFrontendTheme(), path: `${frontendDir}/constants/theme.ts`},
    {content: generateFrontendUtilsIndex(), path: `${frontendDir}/utils/index.ts`},
    {content: generateFrontendEnv(), path: `${frontendDir}/.env`},
    {content: generateFrontendEnvExample(), path: `${frontendDir}/.env.example`},

    // GitHub Actions workflows
    {content: generateBackendCiWorkflow(args), path: ".github/workflows/backend-ci.yml"},
    {content: generateFrontendCiWorkflow(args), path: ".github/workflows/frontend-ci.yml"},
  ];
};
