import type {SidebarsConfig} from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    "README",
    "roadmap",
    {
      items: [{dirName: "tutorials", type: "autogenerated"}],
      label: "Tutorials",
      link: {id: "tutorials/README", type: "doc"},
      type: "category",
    },
    {
      items: [{dirName: "how-to", type: "autogenerated"}],
      label: "How-to guides",
      link: {id: "how-to/README", type: "doc"},
      type: "category",
    },
    {
      items: [
        "reference/api",
        "reference/ui",
        "reference/syncdb",
        "reference/ai",
        "reference/agent-ui-asks",
        "reference/admin-backend",
        "reference/admin-spa",
        "reference/admin-frontend",
        "reference/api-health",
        "reference/announcements",
        "reference/comms",
        "reference/jobs",
        "reference/feature-flags",
        "reference/mcp-server",
        "reference/cli",
        "reference/create-terreno-app",
        "reference/environment-variables",
        {
          items: [{dirName: "reference/generated", type: "autogenerated"}],
          label: "Generated API",
          link: {id: "reference/generated/README", type: "doc"},
          type: "category",
        },
        {
          items: [{dirName: "reference/components", type: "autogenerated"}],
          label: "UI components",
          link: {id: "reference/components/README", type: "doc"},
          type: "category",
        },
      ],
      label: "Reference",
      link: {id: "reference/README", type: "doc"},
      type: "category",
    },
    {
      items: [{dirName: "explanation", type: "autogenerated"}],
      label: "Explanation",
      link: {id: "explanation/README", type: "doc"},
      type: "category",
    },
  ],
};

export default sidebars;
